### ISSUE TITLE
Using enumerize and simple_form behind proxy object 

### ISSUE THREAD

**Issue by bombazook** [brainspec/enumerize#140]
Maybe there should be a part of README that explains using Enumerize behind proxy like Draper. There is no more convenient way to use it with simple_form than explicit proxying of class method :enumerized_attributes or using explicit :collection attribute.

**Comment by filipewl** [comment]
Thanks! This was helpful for me.

I'm using [reform gem](https://github.com/apotonick/reform) and I couldn't get `simple_form` to display an enumerized field with working i18n as a radio. Delegating `enumerized_attributes` to the model's class did the trick.
