### ISSUE TITLE
enumerize make paper_trail not working properly

### ISSUE THREAD

**Issue by williamherry** [brainspec/enumerize#144]
```
enumerize :status, in: {editing: 0, finished: 1, published: 2}, default: :editing, scope: true, predicates: true
```

add this line will make [paper_trail](https://github.com/airblade/paper_trail) not track status changes, I don't know which gem cause this issue, so I just report both, hope this can be fixed soon

**Comment by kaelumania** [comment]
I am currently still facing this issue with `enumerize 1.1.0` and the paper_trail `YAML` serializer

**Comment by shaneog** [comment]
Me too. @kaelumania What version of `paper_trail` are you using?

**Comment by serggl** [comment]
the problem is that changes made to 0.10.1 affected YAML serialization. So if you used older versions previously, and then upgraded (like I did) - you wont be able to parse existing PaperTrail records.

If someone is interested in a workaround, here is the monkey-patch I've used for this:

```
class PaperTrailEnumerizeParser

  def self.load(source)
    root = Psych.parse(source).root
    traverse root
    root.to_ruby
  end

  private

  def self.traverse(none)
    (none.children || []).each_with_index do |c, c_idx|
      if c.tag == '!ruby/string:Enumerize::Value'
        value_idx = c.children.index { |n| n.is_a?(Psych::Nodes::Scalar) && n.value == 'value' }
        none.children[c_idx] = Psych::Nodes::Scalar.new(c.children[value_idx+1].value)
      else
        traverse c
      end
    end
  end
end
```

**Comment by Bajena** [comment]
Hi, I am pretty sure this gist would help some people struggling to make enumerize work with paper_trail:
https://gist.github.com/Bajena/afa01224f87ccbb201c60037987f5911

**Comment by trappist** [comment]
Can this be reopened or is there another issue superseding this one?

**Comment by luizcarvalho** [comment]
Same problem here! =(

Enumerize (1.1.1)
PaperTrail (4.2.0)

**Comment by lest** [comment]
@luizcarvalho The latest enumerize version is 2.0.1. Can you please create a test application reproducing the issue if there is still an issue with the latest version? Thank you!

**Comment by luizcarvalho** [comment]
Thanks @lest still not working.
I try with a new project

### Gemfile
```
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
gem 'enumerize', ' ~> 2.0.1', github: 'brainspec/enumerize'
gem 'paper_trail', '~> 4.2.0'
```

### Model

```
class Document < ApplicationRecord
  extend Enumerize
  enumerize :status, in: [:draft, :released]
  has_paper_trail
end

```

### Testing
```
d = Document.new
d.title = 'a'
d.save
d.versions.last.changeset => nil
```

**Comment by lest** [comment]
@luizcarvalho can you please push that test application so we can figure out a proper fix?

**Comment by luizcarvalho** [comment]
@lest of course!
https://github.com/luizcarvalho/enumerize_paper_trail_test

Ty for attention.

**Comment by lest** [comment]
@luizcarvalho thank you! I'll take a look.

**Comment by lest** [comment]
@luizcarvalho I checked the test application and reproduced the same issue even without enumerize in Gemfile. So this is clearly not an enumerize issue.

However, I also checked paper_trail README and noticed the following:

> he best way to diff adjacent versions is to get PaperTrail to do it for you. If you add an object_changes text column to your versions table, either at installation time with the rails generate paper_trail:install --with-changes option or manually, PaperTrail will store the changes diff (excluding any attributes PaperTrail is ignoring) in each update version. You can use the version.changeset method to retrieve it.

I think that changeset method will work only if an object_changes column is present. Hope this will help.

**Comment by luizcarvalho** [comment]
Ohhh Thanks @lest .

Sorry for that :D

**Comment by xinranxiao** [comment]
The problem @kaelumania posted is still a problem.
