### ISSUE TITLE
Use predicate through delegates

### ISSUE THREAD

**Issue by montells** [brainspec/enumerize#152]
http://stackoverflow.com/questions/23061723/ruby-delegate-enumerize-field

having model with enumerize field

    class ModelB < ActiveRecord::Base
      extend Enumerize
    
      attr_accessible :field_in_delegate
    
      enumerize :field_in_delegate,
                in: {option_one: 1, option_two: 2, option_three: 3},
                default: :option_one, predicates: true, scope: true
    end

I can delegate field_in_delegate when it field is enumerize

    class ModelA < ActiveRecord::Base
      extend Enumerize
    
      attr_accessible :field_in_delegate
    
      delegate :field_in_delegate, to: :modelb
    
      has_one :ModelB  
    end

then I can call

> modelA.field_in_delegate

 without problem but I can't call 
 

>  modelA.option_one?

how can I dry mode access to helpers methods provided by enumerize through delegate

Feature: Delegate helper methods provide by **predicates: true**

  Scenario: Default 
    **Given** ClassB enumerate "ONE" field with values ***in: {option_one: 1, option_two: 2, option_three: 3}***
    **And** ***predicates: true***
    **When** ClassA delegete "ONE" field to ClassB
    **Then** objectA should respond to **option_one?**
    **Then** objectA should respond to **option_tow?**
    **Then** objectA should respond to **option_three?**

**Comment by nashby** [comment]
@montells hey, sorry for the late response. Actually, to make this work we'd need to patch `delegate` method and I don't think it's worth it. Anyway thank you for trying to make enumerize better!
