### ISSUE TITLE
Predicates for old attribute value

### ISSUE THREAD

**Issue by kushkella** [brainspec/enumerize#169]
In Rails we have option to access the old attribute value as long as record is not saved. e.g. if a model has an attribute `sex` we can access its old value by calling `sex_was`. It would be great if enumerize can support the same. So if old value of `sex` attribute is `female`, `female_was?` should return true. Thanks!

**Comment by lest** [comment]
Thanks for you proposal, but this feature looks like something that is not required for all models, and it can be implemented right in the place where it is needed, e.g., by the following snippet:

``` ruby
User.sex.values.each do |value|
  define_method(:"#{value}_was?") do
    sex_was == value
  end
end
```

Frankly, the naming of such methods seems confusing to me. Maybe `was_female?` would be better than `female_was?` in this particular case.

Cheers!
