### ISSUE TITLE
Use underscore.humanize for values in views

### ISSUE THREAD

**Issue by mintuhouse** [brainspec/enumerize#174]
If one of the enumerized values is "API" and it is added to inflections, I would expect it to display as API in views also, but Value#i18n_keys would return Api

In [lib/enumerize/value.rb](https://github.com/brainspec/enumerize/blob/5adb11dea2e69e3a511664bc85436c8c9b273deb/lib/enumerize/value.rb#L39) 
````
i18n_keys << self.humanize
````
could be 
````
i18n_keys << self.underscore.humanize
```` 

[reference](https://github.com/rails/rails/issues/17879)

**Comment by lest** [comment]
Could you please create a pull request with this change? Thanks!
