### ISSUE TITLE
TypeError singleton can't be dumped in 0.10.0 

### ISSUE THREAD

**Issue by jan-harmsen** [brainspec/enumerize#181]
getting ```TypeError singleton can't be dumped`` after upgrading from 0.9.0 to 0.10.0 (rails 3.2.21 with mongoid 3.1.6)

problem does not occur with branch 'predicatable', any chance of having predicatable merged?

Thanks!

**Comment by lest** [comment]
Could you please check the master branch now?

**Comment by jan-harmsen** [comment]
yes, that fixed the bug, awesome, THANKS!

**Comment by lest** [comment]
Thanks for testing! I'm going to prepare 0.10.1 release soon.

**Comment by jan-harmsen** [comment]
wonderful, once again thank you for your quick response and fix :+1: :+1:

**Comment by lest** [comment]
0.10.1 was released.
