### ISSUE TITLE
After changing values in "enumerize", the prior values  display

### ISSUE THREAD

**Issue by DiuDiugirl** [brainspec/enumerize#183]
I am using version 0.7.0 

eg: 
The prior values is

` enumerize :available_start, :in => %w(first_grade second_grade third_grade )`

and then in the front page `available_start`show as a selection with aboved values, and I choose `first_grade`(then it is saved in database).

But when I changed the values of `available_start` to

` enumerize :available_start, :in => %w(first_degree second_degree third_degree )`

In the front page the selections of `available_start` changed but  the prior value doesn't show.

Is this a bug or sth else?

**Comment by DiuDiugirl** [comment]
sorry to bother~
in the show page not the form page, the prior value doesn't show.

**Comment by nashby** [comment]
@DiuDiugirl hey, database knows nothing about the fact that you changed values of the `:available_start` in the enumzerize call. So if you want to make it work you have to sync values of the `available_start` field in your DB with new values in the enumerize method.
