### ISSUE TITLE
mongoid scope bug when chaining the same field

### ISSUE THREAD

**Issue by calfzhou** [brainspec/enumerize#184]
For example I have a collection `Doc`, which contains a field `status` may have values `1..8` and the values are all enumerizes.

The field `status` is defined using
```ruby
  enumerize :status,
            in:         Enumerations.doc_statuses.to_hash,
            scope:      :having_status,
            i18n_scope: 'doc_statuses'
```

Then i use the scope do some querying, such as `Doc.having_status(1, 2)`, and it will generate a correct criteria:
```ruby
#<Mongoid::Criteria
  selector: {"status"=>{"$in"=>[1, 2]}}
  options:  {}
  class:    Doc
  embedded: false>
```

But when I chaining two or more scopes, the former ones will all be overwritten, and will lead incorrect final criteria.

For example a query `Doc.having_status(1, 2).having_status(1, 3)` should generate a `{"status"=>{"$in"=>[1]}}` selector, but it generates `{"status"=>{"$in"=>[1, 3]}}`.

Similarly a query `Doc.having_status(1, 2).union.having_status(1, 3)` should generate `{"status"=>{"$in"=>[1, 2, 3]}}`, but now it also generates an incorrect selector: `{"status"=>{"$in"=>[1, 3]}}`.

**Comment by nashby** [comment]
@calfzhou hey, thank you for letting us know about this issue. It should be fixed in the master branch now.

**Comment by calfzhou** [comment]
Thanks!
