### ISSUE TITLE
Simple way to get all i18n texts for a value

### ISSUE THREAD

**Issue by robj** [brainspec/enumerize#188]
for an enum property Symbolize [ https://github.com/nofxx/symbolize ] has the class method get_#{property_name}_values which dumps a nested array of values and i18n texts for the current locale.

eg.

```
class Linux

  enumerize :distro, :in => [:redhat, :ubuntu, :mint]

end
```

```
> I18n.locale
:en
> Linux.get_distro_values
[ ['redhat', 'Redhat Linux'], ['ubuntu', 'Ubuntu OS'], ['mint', 'Mint Linux'] ]



> I18n.locale
:de
> Linux.get_distro_values
[ ['redhat', 'RotHut Linux'], ['ubuntu', 'Ubuntu Betriebssystem'], ['mint', 'Pfefferminz Linux'] ]
```

This is extremely handy to have (eg. client side Form builders), any way to do this in enumerize?

**Comment by nashby** [comment]
@robj yes, there's `options` method. 

```ruby
Linux.distro.options
```
