### ISSUE TITLE
Support for AASM

### ISSUE THREAD

**Issue by ryansch** [brainspec/enumerize#192]
I only needed to add the following monkey patch to get aasm working.

```ruby
module Enumerize
  class Attribute
    def enum_hash
      @enum_hash ||= values.each_with_object({}) do |value,hash|
        hash[value.to_s] = value.value
      end.with_indifferent_access
    end
  end
end
```

Then in my model:

```ruby
extend Enumerize
enumerize :status, in: {
  active: 0,
  inactive: 1
}

def self.status_enum_hash
  self.status.enum_hash
end

include AASM
aasm column: :status, enum: :status_enum_hash do
  state :active, initial: true
  state :inactive

  # etc
end
```

**Comment by ryansch** [comment]
To be clear, this is to support upgrading from rails 3 to rails 4 with built in enums.  I'm using an integer column to back the status.

**Comment by prem-prakash** [comment]
@ryansch thanks a lot

**Comment by nashby** [comment]
@ryansch hey, thanks for reporting it! I'm gonna close it for now since we don't use aasm at the moment. Also I think most of the apps are already upgraded to rails 4. Cheers!

**Comment by duybn-0885** [comment]
Where u put the monkey-patch module to make it works??

**Comment by ryansch** [comment]
@duybn-0885 You can drop it into a rails initializer.
