### ISSUE TITLE
undefined method in when using both Mongoid & ActiveRecord in same project

### ISSUE THREAD

**Issue by mintuhouse** [brainspec/enumerize#199]
using ````:scope```` option when using both ActiveRecord and Mongoid gives following error
 
````
NoMethodError: undefined method `in' for Vehicle (call 'Vehicle.connection' to establish a connection):Class
from /home/hasan/.rvm/gems/ruby-2.1.6@gogo/gems/activerecord-4.1.11/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
````

**Comment by nashby** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by mintuhouse** [comment]
@nashby I made a small fix which solves the issue for me. Please review.

**Comment by nashby** [comment]
should be fixed by https://github.com/brainspec/enumerize/commit/92696a906b76c91c848e55bb5229f0a187ad7f2b

**Comment by mintuhouse** [comment]
I can confirm that it is fixed in master.

**Comment by nashby** [comment]
@mintuhouse thanks!
