### ISSUE TITLE
You are trying to cache a Ruby object which cannot be serialized to memcached.

### ISSUE THREAD

**Issue by 42thcoder** [brainspec/enumerize#201]
I got a jbuilder to produce JSON, like this: 

```ruby
json.cache! [@user] do 
  json.extract @user, :role
end
```

and here is the User model:

```ruby
class User < ActiveRecord::Base
  enumerize :role, in: { admin: 1, customer: 2, super_admin: 3 }, scope: :with_role
end
```

It keeps telling me that `You are trying to cache a Ruby object which cannot be serialized to memcached.`  Why?  

Looking forward to your reply~  @lest @nashby

**Comment by nashby** [comment]
@42thcoder hey, I added spec 12ef24e79f9e7450a56e3952d6dd219597e509c3 to ensure it's working. What version of enumerize are you using if it's still an issue?
