### ISSUE TITLE
support for minitest >= 5.7 : rename variable 'value' in test/value_test.rb

### ISSUE THREAD

**Issue by boutil** [brainspec/enumerize#202]
Hi,

In order to be able to run the test suite with minitest >= 5.7, the only thing needed is renaming the `:value` test variable in test/value_test.rb to something else, as it conflicts with a method in minitest/spec.
I don't have great imagination, so I propose "val". If it is ok with you or if you have another choice, I can propose a pull request.

**Comment by lest** [comment]
@boutil That would be great!
