### ISSUE TITLE
Named scoped does not define a without_* scope

### ISSUE THREAD

**Issue by kapso** [brainspec/enumerize#210]
Looks like if you define a named scope, it skips the negative/without scope. Why is that?

https://github.com/brainspec/enumerize/blob/aa402d6e9474a2eed6bdc55347db61acd95ac8c5/lib/enumerize/scope/activerecord.rb#L28-L33

**Comment by nashby** [comment]
@kapso it's kinda hard properly name negative scope if you passed a name for a "with" scope. E.g if named it `by_status` naming negative scope `without_by_status` won't be that smart. Feel free to suggest an idea how to fix that (you can even send a PR!). Thanks!
