### ISSUE TITLE
Compatibility with shoulda-matchers v3

### ISSUE THREAD

**Issue by randoum** [brainspec/enumerize#214]
Greetings,

Say I got a model with enumerized attribute for wich I also validate its length
```ruby
class User < ActiveRecord::Base
  enumerize :language, in: %i[en fr]
  validates_length_of :language, is: 2
end
```

Say I am using rspec with [shoulda-matchers](https://github.com/thoughtbot/shoulda-matchers) v3
```ruby
describe User, type: :model do
  it 'validations' do
    is_expected.to validate_length_of(:language).is_equal_to 2
  end
end
```

---

`validate_length_of` works internally by filling up the field with 'x's and test for validation error messages. 

When trying to fill with 'x's, enumerized will [set the value to nil because it is not a valid value](https://github.com/brainspec/enumerize/blob/master/lib/enumerize/attribute.rb#L99) and the test will fail with the message:

> Shoulda::Matchers::ActiveModel::AllowValueMatcher::CouldNotSetAttributeError: Expected Class to be able to set language to "x", but got nil instead.

---

I wrote a simple workaround for it, in form of a spec helper:
```ruby
def enumerize_allowing_values(klass, method, values)
  let!(:original_enumerize_hash) { klass.enumerized_attributes[method].instance_variable_get('@value_hash').dup }
  before do
    hash = values.inject(original_enumerize_hash.dup) { |h, v| h.merge! v => Enumerize::Value.new(self, v) }
    klass.enumerized_attributes[method].instance_variable_set '@value_hash', hash
  end
  after do
    klass.enumerized_attributes[method].instance_variable_set '@value_hash', original_enumerize_hash
  end
end
```
(As you can see, it relies heavily on internal/private of enumerize, which makes it fragile to any changes that could be made)

Anyhow, the spec becomes:
```ruby
describe User, type: :model do
  describe 'validations' do
    enumerize_allowing_values User, :language, %w[x xx xxx]
    it do
      is_expected.to validate_length_of(:language).is_equal_to 2
    end
  end
end
```
And pass

---

Aside of sharing this fact and its workaround, I write this ticket to ask what your guys are thinking: Shall we go ahead and create a Enumerize Rspec matcher/helper to include in enumerize gem along with its test, or shall we talk to shoulda-matchers guys and have them include a workaround in their lib. 

*Before you ask, it is indeed useful to test for length of this field, because the values of the `language` field is meant to change in the future, and the length validation is here to remind to the developers that we correctly set the database field length, and avoid errors dues to truncation.*

**Comment by randoum** [comment]
Updating for multiple fields
```ruby
def enumerize_allowing_values(klass, methods)
  let!(:original_enumerize_hash) do
    methods.keys.inject({}) do |h, method|
      h.merge method => klass.enumerized_attributes[method].instance_variable_get('@value_hash').dup
    end
  end
  before do
    methods.each do |method, values|
      hash = values.inject(original_enumerize_hash[method].dup) do |h, value|
        h.merge value => Enumerize::Value.new(self, value)
      end
      klass.enumerized_attributes[method].instance_variable_set '@value_hash', hash
    end
  end
  after do
    methods.keys.each do |method|
      klass.enumerized_attributes[method].instance_variable_set '@value_hash', original_enumerize_hash[method]
    end
  end
end
```

Usage:
```ruby
enumerize_allowing_values User, language: %w[x xx xxx], status: %w[xxxx xxxxx]
```

**Comment by nashby** [comment]
@randoum hello! What do you think about using [rspec qualifiers](https://github.com/brainspec/enumerize#qualifiers)?

**Comment by randoum** [comment]
I use them. But what does it has to do with my case here?

**Comment by nashby** [comment]
@randoum hey, sorry but we decided not to add support for `validate_length_of` matcher since it looks like pretty unusual case to test length of enumerated attribute. Probably you can use something like this for it:

```ruby
User.language.values.each do |value|
  it "has valid language #{value}" do
    expect(value.size).to eq(2)
  end
end
```

or continue using your workaround. Thanks!

**Comment by randoum** [comment]
@nashby thanks for your answer.

Yes, I systematically perform this kind of test. You seem to believe I am asking for your help or coding inspiration, so I feel obliged to clarify to you that this ticket is not to ask for your help, it is instead to raise to your concern a compatibility problem.

And before closing this parenthesis, let me paste here a much more efficient piece of code for those who may find our conversation :

```
let(:statuses) { %i[idle ready_upload uploading ready_deploy deploying ready_cancel canceling] }
let(:status_limit) { Publication.columns.find{|c| c.name == 'status'}.limit }
it {
  is_expected.to enumerize(:status).in(*statuses).with_default(:idle)

  statuses.each do |status|
    expect(status.length).to be <= status_limit
 end
}
```
---
This being said, I believe you are making a wrong decision here. It may be unusual for you to test database field length over a enumerize field, but it is still a good code consistency test to avoid data truncation. 

So I insist. Kindly give a second thought to the case I raise.
