### ISSUE TITLE
RSpec: Testing in qualifier with custom values.

### ISSUE THREAD

**Issue by DavidVII** [brainspec/enumerize#217]
I've setup a `Reference` model that has a `kind` integer attribute.

```ruby
class Reference < ActiveRecord::Base
  extend Enumerize
  enumerize :kind, in: { contact: 0 }
end
```

The implementation works, but testing this has not. I wrote this up based on [this part](https://github.com/brainspec/enumerize#in) of the README.

```ruby
RSpec.describe Reference, type: :model do
  it { is_expected.to enumerize(:kind).in(contact: 0) }
end
```

Here's the error I get:

```ruby
Failure/Error: it { is_expected.to enumerize(:kind).in(contact: 0) }
expected :kind to allow value: "{:contact=>0}", but it allows "contact" instead
```

Shouldn't this pass? I'm a bit new to this gem, so perhaps I'm missing something? I'm using the latest version 1.0.0. Rails 4.1.11 and Ruby 2.2.3.

**Comment by nashby** [comment]
@DavidVII as I can see this feature wasn't released yet. @lest should we release a new version?

**Comment by lest** [comment]
1.1.0 was released :tada:

**Comment by DavidVII** [comment]
:+1: :confetti_ball: Thanks!
