### ISSUE TITLE
Using enumerize with integers failed

### ISSUE THREAD

**Issue by kaelumania** [brainspec/enumerize#218]
I found a gist from someone else who is getting the same error as I do.

https://gist.github.com/chagar/a0181b3458c77cb72848

I use version 1.0.0 with Rails 3.2, here is the line
`gems/enumerize-1.0.0/lib/enumerize/base.rb:102:in block in _set_default_value_for_enumerized_attributes`

**Comment by onebree** [comment]
I am using Rails 4.1.1, and would like to use the gem. However, I am not willing to change an integer field to a string just to satisfy the gem. (That's the purpose of integer field in the DB anyway.) Is anyone having this issue on newer versions of Rails?

**Comment by lest** [comment]
Closing as Rails 3.2 support was dropped in [version 1.0.0](https://github.com/brainspec/enumerize/blob/master/CHANGELOG.md#100-august-2-2015).

**Comment by onebree** [comment]
@lest I am using Rails 4.1.1 and had an issue using the gem for an integer-type column.

**Comment by lest** [comment]
Can you please push a test application reproducing this issue?

**Comment by onebree** [comment]
@lest I do not know when I will get the time to do that. I will try this week though.

**Comment by lest** [comment]
@onebree Thank you!

**Comment by nashby** [comment]
Closing this for now. I'm not really sure why'd you need to override getter (that's why you're getting that error, without overriding it works properly (according to specs)). Feel free to push test application that reproduces this issue (or even better a failing spec) and I'll reopen it.
