### ISSUE TITLE
ActiveModel::MissingAttributeError when limiting values returned from query

### ISSUE THREAD

**Issue by p3drosola** [brainspec/enumerize#228]
I'm seeing an exception when I limit the attributes returned by a query so that the enumerized attribute is not present.

eg: If my `User` model has a `gender` enum. running `User.all.only(:name).map &:name` throws 

```
ActiveModel::MissingAttributeError: Missing attribute: 'gender'.
```

Using mongoid 4.

**Comment by nashby** [comment]
what version of `enumerize` are you using?

**Comment by p3drosola** [comment]
Thanks for the quick answer! I'm on latest,  `1.1.1`

**Comment by nashby** [comment]
This might be fixed by this PR - https://github.com/brainspec/enumerize/pull/225. Can you please try master branch and report back? Thanks!

**Comment by p3drosola** [comment]
I'm afraid I still get the same error when running  master

**Comment by nashby** [comment]
@p3drosola can you please try master again? I hope I fixed it with latest commit.

**Comment by p3drosola** [comment]
Works great! Thanks.
