### ISSUE TITLE
update_all is failing 

### ISSUE THREAD

**Issue by saten** [brainspec/enumerize#230]
I'm using the latest code from master (because of issue #228 )

My code is the following:
MyModel.increment_counter(:views_count, params[:id])

This now fails with:

ArgumentError: wrong number of arguments (2 for 1)
from /home/docker/myapp/vendor/cache/enumerize-535cc91bf6b8/lib/enumerize/activerecord.rb:45:in `update_all'

**Comment by nashby** [comment]
what rails version are you using?

**Comment by saten** [comment]
It’s 3.2.22.1

**Comment by nashby** [comment]
@saten I see. We dropped Rails 3 support in version 1.0 and this `update_all` override we're using is based on Rails 4 version which accepts only one argument. Not really sure if we should fix that. 
@lest what do you think?

**Comment by saten** [comment]
Feel free to close this issue then. I removed the calls to increment_counter to circumvent the bug, I had only a few in the codebase.

Thank you

**Comment by lest** [comment]
Sorry, but Rails 3 is not supported anymore.
@nashby I think it makes sense to have a note in README about supported Rails versions.
