### ISSUE TITLE
Helper method to quickly changes enum value

### ISSUE THREAD

**Issue by nicolas-besnard** [brainspec/enumerize#240]
One cool thing about Rails' enum is the helper to quickly changes en enum value:

```ruby
model_instance.refused!
```

Is there any way to replicate this on `enumerize` ?

For now, I've created a module with the following code. /!\ It works for me because I only use attribute value for my enum.

```ruby
enumerized_attributes.attributes.each do |enum_attribute, enum|
  enum.values.each do |value|
    define_method "#{enum_attribute}_#{value}!" do
      update!("#{enum_attribute}": enum.public_send(:find_value, value).value)
     end
  end
end
```

**Comment by nashby** [comment]
@nicolas-besnard hey! Thank you for opening this issue but as for me these method names would sound ambiguously (e.g when field name is `sex` and one of the value is `male` so method will look like this: `user.male!`). So I think this feature can live as some enumerize extension in your code if you need it. Cheers!
