### ISSUE TITLE
Does update_all need to be 'enumerized' for array arguments?

### ISSUE THREAD

**Issue by ianwhite** [brainspec/enumerize#243]
Presently update_all is broken for normal string and interpolated array usage.  This pull request fixes that: #242 

But should Enumerize intercept interpolated arrays?

For example:

```
users_to_block.update_all ["status = :status, status_revision = status_revision + 1", {status: :blocked}]
```

**Comment by lest** [comment]
I think it's okay to handle only basic use case with `update_all`.

When a hash is passed to `update_all`, we can be sure that the key is referencing some particular attribute. In a case of passing an array, we cannot know whether it's an attribute being referenced or not. So intercepting interpolated arrays can confuse people.

**Comment by ianwhite** [comment]
Agreed, and it would be tricky to support all  of the interpolation possibilities

But this should probably be made clear in the docs / README
