### ISSUE TITLE
Enumerize::Value support integer

### ISSUE THREAD

**Issue by yakjuly** [brainspec/enumerize#249]
```
class Comparison < ActiveRecod::Base
  enumerize :type_id, in: {
    :less_than => 0,
    :great_than => 1,
  }
end

Comparison.first.to_json 
{"type_id": "less_than"}
```

Enumerize::Value is a String. when generate JSON string, the value will be converted as a string. This will enforce developers to modify code if they did not use Enumerize when project begin.

A Integer Enumerize::Value should be used. when `:in` option is a hash and values are integer.

**Comment by lest** [comment]
Unfortunately, we cannot change it because it will be a breaking change and will require existing Enumerize users to update their code. I don't think that it's worth making such global change at this point in time.

Thanks for your proposal.
