### ISSUE TITLE
NoMethodError: private method `prepend' called for #<Class:Datafile>

### ISSUE THREAD

**Issue by huanzhang** [brainspec/enumerize#254]
I got the following errors on production but didn't find on development:

NoMethodError: private method `prepend' called for #<Class:Datafile>
  /home/deploy/apps/kt-lode-collection/current/vendor/bundle/ruby/gems/enumerize-2.0.0/lib/enumerize/base.rb:5:in `included'
  /home/deploy/apps/kt-lode-collection/current/vendor/bundle/ruby/gems/enumerize-2.0.0/lib/enumerize.rb:31:in `include'
  /home/deploy/apps/kt-lode-collection/current/vendor/bundle/ruby/gems/enumerize-2.0.0/lib/enumerize.rb:31:in `extended'
  /home/deploy/apps/kt-lode-collection/releases/20160812082515Z/app/models/datafile.rb:2:in `extend'
  /home/deploy/apps/kt-lode-collection/releases/20160812082515Z/app/models/datafile.rb:2:in `<class:Datafile>'
  /home/deploy/apps/kt-lode-collection/releases/20160812082515Z/app/models/datafile.rb:1:in `<top (required)>'
  /home/deploy/apps/kt-lode-collection/current/vendor/bundle/ruby/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
  /home/deploy/apps/kt-lode-collection/current/vendor/bundle/ruby/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `block in require'
  /home/deploy/apps/kt-lode-collection/current/vendor/bundle/ruby/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
  /home/deploy/apps/kt-lode-collection/current/vendor/bundle/ruby/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
  /home/deploy/apps/kt-lode-collection/current/vendor/bundle/ruby/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:360:in `require_or_load'
  /home/deploy/apps/kt-lode-collection/current/vendor/bundle/ruby/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:317:in `depend_on'
  /home/deploy/apps/kt-lode-collection/current/vendor/bundle/ruby/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:233:in `require_dependency'
  /home/deploy/apps/kt-lode-collection/current/vendor/bundle/ruby/gems/railties-4.2.5.1/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
  /home/deploy/apps/kt-lode-collection/current/vendor/bundle/ruby/gems/railties-4.2.5.1/lib/rails/engine.rb:471:in `each'
  /home/deploy/apps/kt-lode-collection/current/vendor/bundle/ruby/gems/railties-4.2.5.1/lib/rails/engine.rb:471:in `block in eager_load!'
  /home/deploy/apps/kt-lode-collection/current/vendor/bundle/ruby/gems/railties-4.2.5.1/lib/rails/engine.rb:469:in `each'
  /home/deploy/apps/kt-lode-collection/current/vendor/bundle/ruby/gems/railties-4.2.5.1/lib/rails/engine.rb:469:in `eager_load!'
  /home/deploy/apps/kt-lode-collection/current/vendor/bundle/ruby/gems/railties-4.2.5.1/lib/rails/engine.rb:346:in `eager_load!'
  /home/deploy/apps/kt-lode-collection/current/vendor/bundle/ruby/gems/railties-4.2.5.1/lib/rails/application/finisher.rb:56:in `each'
  /home/deploy/apps/kt-lode-collection/current/vendor/bundle/ruby/gems/railties-4.2.5.1/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
  /home/deploy/apps/kt-lode-collection/current/vendor/bundle/ruby/gems/railties-4.2.5.1/lib/rails/initializable.rb:30:in `instance_exec'
  /home/deploy/apps/kt-lode-collection/current/vendor/bundle/ruby/gems/railties-4.2.5.1/lib/rails/initializable.rb:30:in `run'
  /home/deploy/apps/kt-lode-collection/current/vendor/bundle/ruby/gems/railties-4.2.5.1/lib/rails/initializable.rb:55:in `block in run_initializers'
  /usr/share/ruby/tsort.rb:150:in `block in tsort_each'
  /usr/share/ruby/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
  /usr/share/ruby/tsort.rb:219:in `each_strongly_connected_component_from'
  /usr/share/ruby/tsort.rb:182:in `block in each_strongly_connected_component'
  /usr/share/ruby/tsort.rb:180:in `each'
  /usr/share/ruby/tsort.rb:180:in `each_strongly_connected_component'
  /usr/share/ruby/tsort.rb:148:in `tsort_each'
  /home/deploy/apps/kt-lode-collection/current/vendor/bundle/ruby/gems/railties-4.2.5.1/lib/rails/initializable.rb:54:in `run_initializers'
  /home/deploy/apps/kt-lode-collection/current/vendor/bundle/ruby/gems/railties-4.2.5.1/lib/rails/application.rb:352:in `initialize!'
  /home/deploy/apps/kt-lode-collection/releases/20160812082515Z/config/environment.rb:5:in `<top (required)>'
  config.ru:4:in `require'
  config.ru:4:in `block in <main>'
  /home/deploy/apps/kt-lode-collection/current/vendor/bundle/ruby/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
  /home/deploy/apps/kt-lode-collection/current/vendor/bundle/ruby/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /home/deploy/apps/kt-lode-collection/current/vendor/bundle/ruby/gems/unicorn-5.1.0/lib/unicorn.rb:56:in `eval'
  /home/deploy/apps/kt-lode-collection/current/vendor/bundle/ruby/gems/unicorn-5.1.0/lib/unicorn.rb:56:in `block in builder'
  /home/deploy/apps/kt-lode-collection/shared/vendor/bundle/ruby/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:752:in `call'
  /home/deploy/apps/kt-lode-collection/shared/vendor/bundle/ruby/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:752:in `build_app!'
  /home/deploy/apps/kt-lode-collection/shared/vendor/bundle/ruby/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:129:in `start'
  /home/deploy/apps/kt-lode-collection/current/vendor/bundle/ruby/gems/unicorn-5.1.0/bin/unicorn:126:in `<top (required)>'
  /home/deploy/apps/kt-lode-collection/current/vendor/bundle/ruby/bin/unicorn:23:in `load'
  /home/deploy/apps/kt-lode-collection/current/vendor/bundle/ruby/bin/unicorn:23:in `<top (required)>'

**Comment by lest** [comment]
What Ruby version do you use in production?

**Comment by huanzhang** [comment]
@lest ruby 2.0.0p598 (2014-11-13) [x86_64-linux]

**Comment by lest** [comment]
Unfortunately, this might be the answer why it doesn't work for you. `enumerize` 2.0.0 has dropped support for Ruby 2.0, so it supports only version 2.2 and newer. It is the same minimal Ruby version requirements as in Rails 5.

**Comment by huanzhang** [comment]
@lest thanks!
