### ISSUE TITLE
Booleans break on 'frozen'

### ISSUE THREAD

**Issue by francispotter** [brainspec/enumerize#255]
I think the booleans break on the value 'frozen'.

```ruby
2.3.1 :006 > c.state = 'open'
 => "open" 
2.3.1 :007 > c.state.open?
 => true 
2.3.1 :008 > c.state='frozen'
 => "frozen" 
2.3.1 :009 > c.state.open?
 => false 
2.3.1 :010 > c.state
 => "frozen" 
2.3.1 :011 > c.state.frozen?
 => false 
```

I'm guessing this is because of Ruby's `Object.frozen?` method. It's probably doing the right thing (not overriding the Ruby method) but it might be helpful if the README is updated. Or maybe I'm missing something?

**Comment by nashby** [comment]
@francispotter hey! That's right. We have mention in README about similar issue with Mongoid. Feel free to open a PR with adding warning about Ruby's general reserved words list (not only Mongoid that we have right now) to the README. Thanks!
