### ISSUE TITLE
Strings instead of symbols

### ISSUE THREAD

**Issue by pupeno** [brainspec/enumerize#256]
Shouldn't Enumerize return symbols instead of strings?

```
>> t.actions
#<Enumerize::Set {like}>
>> t.actions.first
"like"
```

My field is defined this way:

```ruby
serialize :actions, Array
enumerize :actions, in: [:like, :reply], multiple: true
```

and the contents of the field look like this:

```
---
- like
```

**Comment by nashby** [comment]
That's intended behaviour. See discussion [here](https://github.com/brainspec/enumerize/issues/32)
