### ISSUE TITLE
update_all isn't overridden properly everywhere

### ISSUE THREAD

**Issue by hfaulds** [brainspec/enumerize#258]
At the same time I noticed https://github.com/brainspec/enumerize/issues/257 I noticed that the `update_all` code doesn't run for other active record classes such as `ActiveRecord::Relation`.

Carrying on using the example from that issue:

We can see the `update_all` code executes and causes an error when called on `User` directly:

```
> User.update_all(sex: :foo);
NoMethodError: undefined method `value' for nil:NilClass
```

However calling it on a relationship or chain class works fine because https://github.com/brainspec/enumerize/blob/c65867580967724479af1bffbfbea05cbfa62db4/lib/enumerize/activerecord.rb#L45 isn't actually called:

```
> User.where(id: 1).update_all(sex: :foo);
```

**Comment by lest** [comment]
Fixed in https://github.com/brainspec/enumerize/pull/260.
