### ISSUE TITLE
Old "_was" predicate method seems broken

### ISSUE THREAD

**Issue by dfabreguette-ap** [brainspec/enumerize#267]
Hi,
I have the following enum in my "Room" class 
```
  def self.statuses
    [:empty, :pending, :rejected, :opened, :closed]
  end
  enumerize :status, in: self.statuses, default: :empty
```

When I try to call in a rails callback :
```
my_room.status_was
```
I get an "undefined method error" but works well on other attributes. Looks like enumerize gem breaked the "_was" old predicate method.

here is my callback  method :
```
  def check_status
    # Those methods seem undefined
    status_was
    status_changed?
    # ....
  end
```
Any idea ?

**Comment by lest** [comment]
Enumerize doesn't override `*_was` methods. Can you please provide a sample application that reproduces the error?

**Comment by dfabreguette-ap** [comment]
All right, stupid error of myself, I was overriding the method doing :
```
status_was = self.status_was
```

**Comment by dfabreguette-ap** [comment]
@lest Ok. 
I'm using Mongoid if that can help.
Sorry for closing it too fast. The methods _was and _changed? are not defined for enumerize field for are defined for other regular fields defined using basic Mongoid syntax.

**Comment by dfabreguette-ap** [comment]
Ok, sorry ... again, definitly a hard friday morning,
I was missing the "field ..." part so ActiveModel was unaware of my "status" attribute.

But the thing is all other features seemed to work fine. It would be awesome to be warned about that for mongoid users.

```
# Defines notification rules linked to closing field
  def self.statuses
    [:empty, :pending, :rejected, :opened, :closed]
  end
  field :status, type: String # <== MISSING !
  enumerize :status, in: self.statuses, default: :empty
```
