### ISSUE TITLE
Issue with i18n values

### ISSUE THREAD

**Issue by przbadu** [brainspec/enumerize#269]
```ruby
[45] pry(main)> AccountHolder.first.gender
  AccountHolder Load (0.5ms)  SELECT  "account_holders".* FROM "account_holders" ORDER BY "account_holders"."id" ASC LIMIT $1  [["LIMIT", 1]]
=> "male"
```

As you can see it gave me `male` where as expected result is `Male`

```ruby
[46] pry(main)> AccountHolder.gender.options
=> [["Male", "male"], ["Female", "female"], ["Other", "other"]]
```

`gender.options` is properly displaying both `key` and `values`.

__Expected__

when I do `AccountHolder.first.gender` it should return result `Male` i18n value.

__Current behavior__

it is returning `male` which is a key.

I can ensure it by:

```ruby
[77] pry(main)> AccountHolder.first.gender.value
  AccountHolder Load (0.4ms)  SELECT  "account_holders".* FROM "account_holders" ORDER BY "account_holders"."id" ASC LIMIT $1  [["LIMIT", 1]]
=> "male"
```

Is it a bug or am I missing something here??

**Comment by nashby** [comment]
It's expected behaviour. For i18n value you have to call either `user.gender.text` or `user.gender_text`.
