### ISSUE TITLE
attr.options method return value confused when Hash as :in options

### ISSUE THREAD

**Issue by bastengao** [brainspec/enumerize#271]
```
class User < ActiveRecord::Base
  extend Enumerize

  enumerize :role, in: {:user => 1, :admin => 2}
end
```

```
# Actual result
User.role.options # { "User": "user",  "Admin": "admin" }

# But I expect result
User.role.options # { "User": 1,  "Admin": 2 }
```

The integer value is I want to store to DB, not the enum name.

**Comment by lest** [comment]
The integer value will be stored in the DB if you use `User.role.options` for the select on the form. `enumerize` is designed to abstract integer values and represent them with human readable identifiers. For example, if you do `user.role = 'admin'` then `2` will be stored in the `role` column.

**Comment by bastengao** [comment]
@lest Thanks for your quick answer. Actually I use `User.role.options` in search form with `ransack` gem. But it doesn't work because the query value is the enum name not the value.

**Comment by lest** [comment]
@bastengao You can use the following snippet to get the hash you expected:

``` ruby
User.role.values.map { |v| [v.text, v.value] }
```

**Comment by bastengao** [comment]
@lest It works. Thanks.

**Comment by zlx** [comment]
@lest Nice, It helps.
