### ISSUE TITLE
undefined method `include?' for nil:NilClass

### ISSUE THREAD

**Issue by plindelauf** [brainspec/enumerize#277]
We're processing a video file with DelayedJob. When the job finishes, the video file status is checked and updated. The status is "enumerized". 

However, the DelayedJob halts when it deserializes the video object with the error message `undefined method 'include?' for nil:NilClass`. This started to happen in version 2.1.0. For now, I reverted to 2.0.1.

This seem to happen on the following line in the DelayedJob code base:

    @payload_object ||= YAML.load_dj(handler)

Here's the whole serialized object: 

    Job failed to load: undefined method `include?' for nil:NilClass. Handler: "--- !ruby/object:Delayed::PerformableMethod
    object: !ruby/object:Video
      raw_attributes:
        status: ready_to_copy_files
        id: '6132'
        original_name: Fireworks.mp4
        original_width: '1920'
        original_height: '1080'
        original_job_id: '68723660'
        mp4_url: https://s3.amazonaws.com/xxxx/videos/4156/2017/04/20/15/49/26/750Fireworks_enc.mp4
        mp4_job_id: '161500600'
        webm_url: https://s3.amazonaws.com/xxxx/videos/4156/2017/04/20/15/49/26/750Fireworks_enc.webm
        webm_job_id: '161500599'
        thumb_url: https://s3.amazonaws.com/xxxx/videos/4156/2017/04/20/15/49/26/750t_Fireworks_0000.jpg
        thumb_width: '1280'
        thumb_height: '720'
        catalog_thumb_url: https://s3.amazonaws.com/xxxx/videos/4156/2017/04/20/15/49/26/750ct_Fireworks_0000.jpg
        catalog_thumb_width: '100'
        catalog_thumb_height: '56'
        created_at: '2017-04-20 15:27:39.072838'
        updated_at: &7 2017-04-20 15:49:30.158658149 Z
        original_url: https://s3.amazonaws.com/xxxx/videos/4156/2017/04/20/15/49/26/750Fireworks.mp4
        dashboard_id: '4156'
        creation_id: '6132'
      attributes: !ruby/object:ActiveRecord::AttributeSet
        attributes: !ruby/object:ActiveRecord::LazyAttributeHash
          types:
            id: &3 !ruby/object:ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Integer
              precision: 
              scale: 
              limit: 
              range: !ruby/range
                begin: -2147483648
                end: 2147483648
                excl: true
            original_name: &1 !ruby/object:ActiveRecord::Type::String
              precision: 
              scale: 
              limit: 255
            original_width: *1
            original_height: *1
            original_job_id: *1
            status: &5 !ruby/object:Enumerize::ActiveRecordSupport::Type
              attr: !ruby/object:Enumerize::Attribute
                klass: !ruby/class 'Video'
                name: :status
                values:
                - pending
                - transcoding
                - finished
                - failed
                - ready_to_copy_files
                value_hash:
                  pending: pending
                  transcoding: transcoding
                  finished: finished
                  failed: failed
                  ready_to_copy_files: ready_to_copy_files
                default_value: pending
              subtype: *1
            mp4_url: &2 !ruby/object:ActiveRecord::Type::String
              precision: 
              scale: 
              limit: 1000
            mp4_job_id: *1
            webm_url: *2
            webm_job_id: *1
            thumb_url: *2
            thumb_width: *3
            thumb_height: *3
            catalog_thumb_url: *2
            catalog_thumb_width: *3
            catalog_thumb_height: *3
            created_at: &6 !ruby/object:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter
              subtype: &4 !ruby/object:ActiveRecord::ConnectionAdapters::PostgreSQL::OID::DateTime
                precision: 
                scale: 
                limit: 
            updated_at: &8 !ruby/object:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter
              subtype: *4
            original_url: *2
            dashboard_id: *3
            creation_id: *3
          values:
            id: '6132'
            original_name: Fireworks.mp4
            original_width: '1920'
            original_height: '1080'
            original_job_id: '68723660'
            status: ready_to_copy_files
            mp4_url: https://s3.amazonaws.com/xxxx/videos/2013/12/09/23/13/18/368/Fireworks_enc.mp4
            mp4_job_id: '161500600'
            webm_url: https://s3.amazonaws.com/xxxx/videos/2013/12/09/23/13/18/368/Fireworks_enc.webm
            webm_job_id: '161500599'
            thumb_url: https://s3.amazonaws.com/xxxx/videos/2013/12/09/23/13/18/368/t_Fireworks_0000.jpg
            thumb_width: '1280'
            thumb_height: '720'
            catalog_thumb_url: https://s3.amazonaws.com/xxxx/videos/2013/12/09/23/13/18/368/ct_Fireworks_0000.jpg
            catalog_thumb_width: '100'
            catalog_thumb_height: '56'
            created_at: '2017-04-20 15:27:39.072838'
            updated_at: '2017-04-20 15:27:39.072838'
            original_url: https://s3.amazonaws.com/xxxx/videos/2013/12/09/23/13/18/368/Fireworks.mp4
            dashboard_id: '4156'
            creation_id: '6132'
          additional_types: {}
          materialized: true
          delegate_hash:
            status: !ruby/object:ActiveRecord::Attribute::FromDatabase
              name: status
              value_before_type_cast: ready_to_copy_files
              type: *5
              value: ready_to_copy_files
            id: !ruby/object:ActiveRecord::Attribute::FromDatabase
              name: id
              value_before_type_cast: '6132'
              type: *3
              value: 6132
            original_name: !ruby/object:ActiveRecord::Attribute::FromDatabase
              name: original_name
              value_before_type_cast: Fireworks.mp4
              type: *1
              value: Fireworks.mp4
            original_width: !ruby/object:ActiveRecord::Attribute::FromDatabase
              name: original_width
              value_before_type_cast: '1920'
              type: *1
              value: '1920'
            original_height: !ruby/object:ActiveRecord::Attribute::FromDatabase
              name: original_height
              value_before_type_cast: '1080'
              type: *1
              value: '1080'
            original_job_id: !ruby/object:ActiveRecord::Attribute::FromDatabase
              name: original_job_id
              value_before_type_cast: '68723660'
              type: *1
              value: '68723660'
            mp4_url: !ruby/object:ActiveRecord::Attribute::FromUser
              name: mp4_url
              value_before_type_cast: https://s3.amazonaws.com/xxxx/videos/4156/2017/04/20/15/49/26/750Fireworks_enc.mp4
              type: *2
              value: https://s3.amazonaws.com/xxxx/videos/4156/2017/04/20/15/49/26/750Fireworks_enc.mp4
            mp4_job_id: !ruby/object:ActiveRecord::Attribute::FromDatabase
              name: mp4_job_id
              value_before_type_cast: '161500600'
              type: *1
              value: '161500600'
            webm_url: !ruby/object:ActiveRecord::Attribute::FromUser
              name: webm_url
              value_before_type_cast: https://s3.amazonaws.com/xxxx/videos/4156/2017/04/20/15/49/26/750Fireworks_enc.webm
              type: *2
              value: https://s3.amazonaws.com/xxxx/videos/4156/2017/04/20/15/49/26/750Fireworks_enc.webm
            webm_job_id: !ruby/object:ActiveRecord::Attribute::FromDatabase
              name: webm_job_id
              value_before_type_cast: '161500599'
              type: *1
              value: '161500599'
            thumb_url: !ruby/object:ActiveRecord::Attribute::FromUser
              name: thumb_url
              value_before_type_cast: https://s3.amazonaws.com/xxxx/videos/4156/2017/04/20/15/49/26/750t_Fireworks_0000.jpg
              type: *2
              value: https://s3.amazonaws.com/xxxx/videos/4156/2017/04/20/15/49/26/750t_Fireworks_0000.jpg
            thumb_width: !ruby/object:ActiveRecord::Attribute::FromDatabase
              name: thumb_width
              value_before_type_cast: '1280'
              type: *3
              value: 1280
            thumb_height: !ruby/object:ActiveRecord::Attribute::FromDatabase
              name: thumb_height
              value_before_type_cast: '720'
              type: *3
              value: 720
            catalog_thumb_url: !ruby/object:ActiveRecord::Attribute::FromUser
              name: catalog_thumb_url
              value_before_type_cast: https://s3.amazonaws.com/xxxx/videos/4156/2017/04/20/15/49/26/750ct_Fireworks_0000.jpg
              type: *2
              value: https://s3.amazonaws.com/xxxx/videos/4156/2017/04/20/15/49/26/750ct_Fireworks_0000.jpg
            catalog_thumb_width: !ruby/object:ActiveRecord::Attribute::FromDatabase
              name: catalog_thumb_width
              value_before_type_cast: '100'
              type: *3
              value: 100
            catalog_thumb_height: !ruby/object:ActiveRecord::Attribute::FromDatabase
              name: catalog_thumb_height
              value_before_type_cast: '56'
              type: *3
              value: 56
            created_at: !ruby/object:ActiveRecord::Attribute::FromDatabase
              name: created_at
              value_before_type_cast: '2017-04-20 15:27:39.072838'
              type: *6
              value: 2017-04-20 15:27:39.072838000 Z
            updated_at: !ruby/object:ActiveRecord::Attribute::FromUser
              name: updated_at
              value_before_type_cast: *7
              type: *8
              value: *7
            original_url: !ruby/object:ActiveRecord::Attribute::FromUser
              name: original_url
              value_before_type_cast: https://s3.amazonaws.com/xxxx/videos/4156/2017/04/20/15/49/26/750Fireworks.mp4
              type: *2
              value: https://s3.amazonaws.com/xxxx/videos/4156/2017/04/20/15/49/26/750Fireworks.mp4
            dashboard_id: !ruby/object:ActiveRecord::Attribute::FromDatabase
              name: dashboard_id
              value_before_type_cast: '4156'
              type: *3
              value: 4156
            creation_id: !ruby/object:ActiveRecord::Attribute::FromDatabase
              name: creation_id
              value_before_type_cast: '6132'
              type: *3
              value: 6132
      new_record: false
      active_record_yaml_version: 0
    method_name: :start_pending_file_copy_without_delay
    args: []
    "
    /app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/backend/base.rb:77:in `rescue in payload_object'
    /app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/backend/base.rb:75:in `payload_object'
    ...

**Comment by lest** [comment]
Can you please push a test application reproducing this issue? It would be very helpful.

**Comment by plindelauf** [comment]
I'll try... I'm very busy at the moment.

**Comment by kreintjes** [comment]
Same problem over here when using ActiveRecord serialize (http://api.rubyonrails.org/v4.2/classes/ActiveRecord/AttributeMethods/Serialization/ClassMethods.html#method-i-serialize).

**Comment by lest** [comment]
@kreintjes Could you please provide an example app that replicates your issue?

**Comment by AdrienGiboire** [comment]
@lest Give a try with this: https://github.com/AdrienGiboire/enumerize-test-app

So far, I think it's related to rails version:
- works against rails `5.1.1`
- fails against rails `5.0.2`/`5.0.3`

**Comment by lest** [comment]
@AdrienGiboire Thank you!

Fixed in the version 2.1.2.
