### ISSUE TITLE
Trouble loading models with multiple values

### ISSUE THREAD

**Issue by smmcbride** [brainspec/enumerize#280]
I'm trying to use the multiple option for the first time and I'm having trouble reloading the values from a saved record.  

My (simplified) model is this:
```
class Product < ActiveRecord::Base
  extend Enumerize

  enumerize :regions, in: [:all, :us, :europe, :asia],
                      default: [:all],
                      multiple: true

  validates_presence_of :name
end
```

And this is what I get when I try to save and reload a model:
```
>> p = Product.new name:"New"
=> #<Product:0x007ffb9005c858 id: nil, name: "New", regions: "[\"all\"]">
[>> p.valid?
=> true

 >> p.save
   (0.3ms)  BEGIN
  SQL (3.5ms)  INSERT INTO "products" ("name", "regions") VALUES ($1, $2) RETURNING "id"  [["name", "New"], ["regions", "[\"all\"]"]]
   (2.5ms)  COMMIT
=> true

>> p = Product.last
  Product Load (1.0ms)  SELECT  "products".* FROM "products"  ORDER BY "products"."id" DESC LIMIT 1
=> #<Product:0x007ffb915bf880 id: 2, name: "New", regions: "[]">

 >> p.valid?
=> false
```

If i inspect my DB I can see that `["all"]` is persisted, but it fails to resolve when the model is reloaded. Am I doing something obviously incorrect in my definition?

I'm using version `2.1.0` of enumerize.

**Comment by nashby** [comment]
@smmcbride do you have `serialize :regions, Array` for your array field?

**Comment by smmcbride** [comment]
Ah, I updated from a single-select and that's what I was missing, thanks @nashby !
