### ISSUE TITLE
SystemStackError: stack level too deep - when using scopes with one enum value

### ISSUE THREAD

**Issue by gambala** [brainspec/enumerize#282]
I have enumerize field in model:

```
class Task < ApplicationRecord
  extend Enumerize

  STATUSES = %i(draft unchecked refused open overdue
                destroyed progress unfulfilled fulfilled).freeze

  enumerize :status,
            in: STATUSES,
            default: STATUSES.first,
            scope: true
end
```

When I trying to scope tasks with one status (for example `Task.with_status(:refused)`), I get `SystemStackError: stack level too deep` error.

When I scoping tasks with many statuses (for example `Task.with_status(:refused, :destroyed)`), I get proper ActiveRecord collection as expected.

`Task.where(status: :refused)` - same error.
`Task.where(status: [:refused])` - proper results.

ruby 2.4.1, rails 5.1, enumerize 2.1.0

UPD: No errors in master branch version, so with `gem 'enumerize', github: 'brainspec/enumerize'` scopes work as expected without any errors.

**Comment by lest** [comment]
Hi @gambala! Thanks a lot for testing the master branch! I released 2.1.1 version based on the latest master.
