### ISSUE TITLE
Problem with rails 5.1 rails_admin 1.2.0 and enumerize 2.1.2

### ISSUE THREAD

**Issue by prem-prakash** [brainspec/enumerize#286]
rails 5.1
rails_admin 1.2.0
enumerize 2.1.2

Edit form does not load record value

maybe related to https://github.com/sferik/rails_admin/issues/2669

**Comment by lest** [comment]
Could you please provide an example app that replicates your issue?

**Comment by prem-prakash** [comment]
If I use enumerize 2.0.1 it works fine

Yes I will do it

**Comment by prem-prakash** [comment]
It is here:
https://github.com/prem-prakash/enumerize-286

**Comment by nashby** [comment]
@prem-prakash hey! This issue should be fixed in master branch. Can you please try it and see if that works? Thanks!

**Comment by prem-prakash** [comment]
It is working now!
