### ISSUE TITLE
Unexpected behavior upgrading to 2.1.1 with  enumerized hash with integer values

### ISSUE THREAD

**Issue by stephen-puiszis** [brainspec/enumerize#292]
Hi folks. Thanks for writing a great gem. I'm in the process of trying to upgrade a rails app from 4.2 -> 5.x and am running into some unexpected behavior while upgrading enumerize to `2.1.1` .

### Code
**Schema** (condensed for brevity) 
```
create_table "goals", force: :cascade do |t|
   t.integer  "priority",                 default: 1,      null: false
   t.integer  "target_score",        default: 0,     null: false
   t.integer  "actual_score",        default: 0,     null: false
end
```
**Model** (condensed for brevity) 
```
# goal.rb 
class Goal < ApplicationRecord
  LIKERT_SCORE = { blank: 0, poor: 1, fair: 2, average: 3, good: 4, excellent: 5 }.freeze

   enumerize :priority, in: { high: 0, medium: 1, low: 2 }, default: :medium, predicates: { prefix: true }
   enumerize :target_score, in: LIKERT_SCORE, default: 0
   enumerize :actual_score, in: LIKERT_SCORE, default: 0
end
```

### What I was expecting (`v1.1.1`)

Previously, initializing a new object would use the default values set by the database and the exact value of the default option. I setup the columns as integers for the purpose of doing math on these enumerized columns and for performance reasons would prefer to off-load these calculations to the DB level rather than perform memory. On the display-side to users, I am making use of enumerize's i18n features.

```ruby
[1] pry(main)> Goal.new
=> #<Goal:0x007fec65248160  id: nil, priority: 1,  target_score: 0, actual_score: 0>
```

### What I'm getting now (`v2.1.1`)

Now, I'm getting the enumerized value on initialization, which is causing a lot of issues in various spots. 

```ruby
[1] pry(main)> Goal.new
=> #<Goal:0x007fd25adea920, id: nil, priority: "medium",  target_score: "blank",  actual_score: "blank">
```
### Questions 
1. I went through the changelog to see if there were any breaking changes prior to upgrading and didn't see anything that looked like it would cause any issues. So this makes me wonder, is my usage beyond the scope of what `enumerize` is intended for, or does this look like a regression? 
2. If this is a bug, I'd be happy to open a PR. A little pointing in the right direction would be lovely.

**Comment by lest** [comment]
Hi Stephen!

The behavior has changed because of implementing a custom Active Record column type that allows to have proper enumerized values and have AR objects serialization working which is needed in order to work correctly together with other gems (for example, with paper_trail). The changes were made in 2.1.0 and weren't supposed to break anything unless the app relies on how exactly enumerize wraps values.

> Now, I'm getting the enumerized value on initialization, which is causing a lot of issues in various spots.

Could you please describe what kind of issues in various spots you are having? It would be very helpful if you could push a sample app reproducing those issues. Thanks!

**Comment by stephen-puiszis** [comment]
@lest Thanks for your reply and for the context! 

I misspoke with regards to "I'm getting the enumerized values on object initialization". This doesn't actually appear to be the problem;  I initially thought it was because it was one of the first behavior changes I noticed. 

The real issue is with ActiveRecord validations, specifically `numericality` validations. From what it looks like, a newly initialized, non-persisted object is valid and will be successfuly saved to the database on create. However, numericality validations fail when the object has already been persisted or on an update. I have a couple specs that demonstrate this in the test app I linked to. Also, some `Shoulda` db column specs fail, but that's probably a `Shoulda` issue, although could be related to the custom column type you mentioned. Please let me know if this is at all helpful. 

https://github.com/stephen-puiszis/rails-5-enumerize

```
[1] pry(#<RSpec::ExampleGroups::Goal::Validations>)> obj = described_class.new
=> #<Goal:0x007fb0169c5a40 id: nil, target_score: "blank", actual_score: "blank", created_at: nil, updated_at: nil>
[2] pry(#<RSpec::ExampleGroups::Goal::Validations>)> obj.valid?
=> true
[3] pry(#<RSpec::ExampleGroups::Goal::Validations>)> obj.save
=> true
[4] pry(#<RSpec::ExampleGroups::Goal::Validations>)> obj.reload
=> #<Goal:0x007fb0169c5a40 id: 9, target_score: "blank", actual_score: "blank", created_at: Fri, 04 Aug 2017 03:48:06 UTC +00:00, updated_at: Fri, 04 Aug 2017 03:48:06 UTC +00:00>
[5] pry(#<RSpec::ExampleGroups::Goal::Validations>)> obj.valid?
=> false
[6] pry(#<RSpec::ExampleGroups::Goal::Validations>)> obj.errors
=> #<ActiveModel::Errors:0x007fb017ec75b0
 @base=
  #<Goal:0x007fb0169c5a40 id: 9, target_score: "blank", actual_score: "blank", created_at: Fri, 04 Aug 2017 03:48:06 UTC +00:00, updated_at: Fri, 04 Aug 2017 03:48:06 UTC +00:00>,
 @details={:target_score=>[{:error=>:not_a_number, :value=>"blank"}], :actual_score=>[{:error=>:not_a_number, :value=>"blank"}]},
 @messages={:target_score=>["is not a number"], :actual_score=>["is not a number"]}>
[7] pry(#<RSpec::ExampleGroups::Goal::Validations>)> obj.actual_score = 2
=> 2
[8] pry(#<RSpec::ExampleGroups::Goal::Validations>)> obj.valid?
=> false
```

### Other Notes That May or May Not Be Useful

I initially was trying to make smaller jumps for this upgrade but while doing some version testing I found that is that I had more spec failures when on Rails `5.0.4` and `5.1.0` than `5.1.3`. With `5.1.0` I was specifically getting getting errors of the sort: `TypeError, comparison with string and integer failed` when the `numericality` validation ran. I noticed I wasn't getting this error on test app I put together that was on `5.1.3` so I upgraded to that version and now the only issue that remain for me are the validations I posted above. It does appear `ActiveModel` had a [regression or two](https://github.com/rails/rails/pull/29249) but this doesn't look related. 

I originally thought the problem was related to a change I noticed when a new object was initialized and the type of values assigned for those enumerized columns: 

- In `1.1.1`, `Goal.new` will initialize and object with integer values as specified by the db schema defaults: `target_score: 0, actual_score: 0` 
- In `2.1.1`, `Goal.new` will initialize an object with the enumerized string values with `target_score: "blank",  actual_score: "blank`

In the test app on `2.1.1`, I also messed around with/without the `enumerize :my_column, default: 0` and either way a new object will be initialized with enumerized string, rather than an integer like in `1.1.1`. This doesn't appear to be negatively impacting any behavior from what I've seen thus far.

**Comment by stephen-puiszis** [comment]
@lest Wanted to check-in and see what you think about all this. Does this seem to be a legitimate issue?

**Comment by stephen-puiszis** [comment]
@lest Any thoughts?

**Comment by alencarandre** [comment]
I'm having the same problem. I'm using schema validation gem and put a integer field with null: false in migration. When the model is validated, throw error becouse the schema validation gem use numericality to validade model.

**Comment by nashby** [comment]
@alencarandre hey! To make it work you need to disable `schema_validations`'s automatically created `numericality` validation on your enumerized field (with something like this https://github.com/SchemaPlus/schema_validations#use-a-custom-validation-rather-than-schema_validations-automatic-default)
