### ISSUE TITLE
How to use predicates with except/only options?

### ISSUE THREAD

**Issue by Extazystas** [brainspec/enumerize#295]
I wonder how to use `except` and `only` options. I found it in code here: https://github.com/brainspec/enumerize/blob/c65867580967724479af1bffbfbea05cbfa62db4/lib/enumerize/predicates.rb

But there are no examples how it works. E.g. I have a simple_form with enumerized `status` field. I don't want to show all options in form, so I've tried add `except` option everywhere, but nothing happens. Way to solve this as I can see - set up collection manually. Maybe someone can explain me how to use it properly? Thanks 🍻 

My code:
```
enumerize :status, in: [:active, :under_repair, :inactivated, :in_transfer], default: :active, scope: true, predicates: { except: [:in_transfer] }
# form:
<%= f.input :status, as: :radio_buttons %>
```

**Comment by joostliketoast** [comment]
running into the same issue, anyone have a recommendation for this?

**Comment by martinGerez** [comment]
Hey, I've no idea if you have been solved this problem.

I think that I discovered the use case for it:

The `.options` method, receives a hash, in which you can pass the keywords `only` or `except`.
I discovered it, digging into this file and line: https://github.com/brainspec/enumerize/blob/88bcdf40a824e040a5c11063116ff1d03bbdb4b9/lib/enumerize/attribute.rb#L65

A simple use case from my project: 
```
AccountProperty.account_type.options(except: %i(client supplier))
```

Hope it helps you. :)
