### ISSUE TITLE
How could I filter records with multiple attributes

### ISSUE THREAD

**Issue by georgechang0117** [brainspec/enumerize#299]
Hi,
I use enumerize with mysql.
I wanna know how could I filter records with multiple attributes
The scope option only supports without multiple attributes mode.

So the only way to make it is using sql __LIKE__ operator?
Is there any better way or suggestion?

Thanks.

**Comment by nashby** [comment]
@georgechang0117 hey, please check this issue for more info https://github.com/brainspec/enumerize/issues/113
