### ISSUE TITLE
Fails when key names are same for 2 separate enumerations

### ISSUE THREAD

**Issue by kapso** [brainspec/enumerize#300]
```ruby
enumerize :role_enum, in: { primary: 10, standby: 20 }, predicates: true, scope: true
enumerize :original_role_enum, in: { primary: 10, standby: 20 }, predicates: true, scope: true
```

```ruby
model.role_enum
=> "primary"
model.primary? # Does not work
=> nil
```

But if I remove `original_role_enum` enumeration or if I change the key names/symbol for `original_role_enum` hash then it works -

```ruby
# with - enumerize :original_role_enum, in: { primary1: 10, standby1: 20 }, predicates: true, scope: true

model.role_enum
=> "primary"
model.primary?
=> true
```

**Comment by lest** [comment]
I see that you have the `predicates: true` option for both enums. So they both define predicate methods (like, `primary?`) and the second definition overrides the first one.

I guess you would want to have `primary?` method work based on `role_enum` value. In this case, you can just remove `predicates: true` from the `original_role_enum` definition.

**Comment by kapso** [comment]
Ah yes, of course, its late in the night here, sorry : )
