### ISSUE TITLE
Rails version is not specified for v2

### ISSUE THREAD

**Issue by stahor** [brainspec/enumerize#302]
I've installed enumerize 2.1.2 into rails 4.1.5 project and now I'm getting the following error.
```
....rvm/gems/ruby-2.3.3@widgety/gems/enumerize-2.1.2/lib/enumerize/activerecord.rb:69:in `<module:ActiveRecordSupport>': uninitialized constant ActiveRecord::Type (NameError)
```
AFAIR AR::Type was added in rails 5 so it would be better to specify minimal rails version somewhere.

**Comment by nashby** [comment]
@stahor hey! Enumerize v2 supports Rails 4.2+. I added info about supported version here https://github.com/brainspec/enumerize#supported-versions. Thanks for letting us know!
