### ISSUE TITLE
Enumerize messes up Arel "LIKE" queries

### ISSUE THREAD

**Issue by zor-el** [brainspec/enumerize#304]
This is quite a nasty issue because of its rather broad impact. It disrupts the operation of other gems that rely on Arel, most notably the Ransack gem where any "contains"-type search on an enumerized field gives the wrong results.

Enumerize version: 2.1.2

Reproduce:

```ruby
class User < ApplicationRecord
  extend Enumerize
  enumerize :role, in: [:user, :a_admin, :b_admin], predicates: true
end
```
```
t = User.arel_table
puts User.where(t[:role].matches '%admin%').to_sql
```

Outcome:

```sql
SELECT "users".* FROM "users" WHERE ("users"."role" LIKE NULL) -- LIKE NULL ?!?
```

Expected outcome (this *is* produced w/o the `enumerize` line):

```sql
SELECT "users".* FROM "users" WHERE ("users"."role" LIKE "%admin%")
```

**Comment by nashby** [comment]
Hey @zor-el! Thanks for reporting this issue! I've created a PR fixing this issue. Could you please it out? https://github.com/brainspec/enumerize/pull/305

**Comment by zor-el** [comment]
Hey there! Your fix works for me! Eagerly awaiting the merge, better yet, the bugfix release so I can bundle it with my project. Great work!

**Comment by zor-el** [comment]
I figured close the issue once the fix is merged.

**Comment by zor-el** [comment]
Uhm, after looking at the fix again, I think serialize now always returns the raw value. Let me elaborate. The fix was done in the `Enumerize::ActiveRecord::Type#serialize`, which now has the code:

```ruby
def serialize(value)
  v = @attr.find_value(value)
  (v && v.value) || value
end
```

After expanding `@attr.find_value` (and imagining there was an `attr_reader` for `value_hash`), it is equivalent to:

```ruby
def serialize(value)
  v = @attr.value_hash[value.to_s] unless value.nil?
  (v && v.value) || value
end
```

Which means the return value is `value.to_s` if that is found in the `value_hash`, or `value` if it is not.

Hence, we can just as well go for the simpler and faster implementation:

```ruby
def serialize(value)
  value.to_s
end
```

What do you think?

**Comment by nashby** [comment]
@zor-el hm, don't think it always returns passed value. Why do you think so? We even have test that checks it https://github.com/brainspec/enumerize/blob/master/test/activerecord_test.rb#L513

And no, we can't use `value.to_s` since we need to support custom values like `enumerize :role, in: {:user => 1, :admin => 2}`

**Comment by zor-el** [comment]
Uh, okay, I wasn't aware of that use case. The way I've been always using it (`enumerize :foo, in: [:bar, :baz]`) it would have. Sorry for the noise.

**Comment by nashby** [comment]
@zor-el no worries! Thanks for looking into it! ❤️

**Comment by zor-el** [comment]
@nashby, but when I think about it, isn't serialize supposed to transform *into* the database representation of the value? And isn't the database representation of an enumized attribiute always a string? And wouldn't that be the *key* also in a case like `enumerize :foo, in: { bar: 1, baz: 2 }`?

I.e. if serialize('bar') would return 1, then 1 would be stored in the database instead of 'bar', which IMO wouldn't be correct.

**Comment by nashby** [comment]
@zor-el 

>  And isn't the database representation of an enumized attribiute always a string?
Not really. The whole point of `enumerize :foo, in: { bar: 1, baz: 2 }` is to store values as integers in DB and show it as `bar` or `baz` when you get it from the DB.

**Comment by zor-el** [comment]
I see.

Because deserialization seems to work even when only the keys are stored in the database. For ex., when I change my enumerize line from my above code into

```ruby
enumerize :role, in: {user: 1, a_admin: 2, b_admin: 3}, predicates: true
```

everything works just as before, even though my database has 'user', 'b_admin' etc. stored in it.
