### ISSUE TITLE
Error raised when using simple form with object without `to_model`

### ISSUE THREAD

**Issue by PikachuEXE** [brainspec/enumerize#309]
I use custom form object classes built with `dry-struct`
It doesn't have `to_model` method and will raise `NoMethodError` since `enumerize` `2.2.0`

**Comment by nashby** [comment]
@PikachuEXE do you have `model_name` method defined in your form objects? I tried to fix that and write test but looks like `SimpleForm` uses `model_name` method internally so it depends on ActiveModel anyway.

**Comment by PikachuEXE** [comment]
SimpleForm uses `object_name` which is from `action_view` form helper
And form helper use option `as` before using `model_name`
https://github.com/rails/rails/blob/5-2-stable/actionview/lib/action_view/helpers/form_helper.rb#L441

**Comment by nashby** [comment]
@PikachuEXE hey, should be fixed in master!

**Comment by PikachuEXE** [comment]
I confirmed this issue is fixed on `master`
Thanks :)

Let me know when new version released ;)

**Comment by lest** [comment]
@PikachuEXE Thank you for confirming the fix. I've released 2.2.2.
