### ISSUE TITLE
Support for ActiveRecord::Enum methods for supporting easy migration

### ISSUE THREAD

**Issue by amratab** [brainspec/enumerize#310]
I have used ActiveRecord::Enum for my enums but need a few extra capabilities like default. All my code still uses methods available with ActiveRecord::Enum like statuses lists all status integer values for enum status. Is there a plan to provide support for such methods to support easy migration?

**Comment by nashby** [comment]
@amratab Hey, we don't have plans on implementing such support but feel free to send a PR!
