### ISSUE TITLE
Setting locale manually to enumerize

### ISSUE THREAD

**Issue by abahaggag** [brainspec/enumerize#312]
First of all I'd like to thank all enumerize gem maintainers for the great job they accomplished. 

I'm using enumerize in all reports which includes translations and works perfectly in most reports expect when report viewed in two different languages say English and Arabic in the same page. So in this case I cannot fetch translations for specific language I want. 

Is there any way to set locale privately for enumerize manually so I have full control when fetching translations for different attributes so instead reading from I18n.locale can enumerize first check inner locale attribute otherwise it reads from I18n.locale?

**Comment by nashby** [comment]
@abahaggag hey, thanks for kind words! 

I think you can achieve something like that with [`I18n.with_locale`](http://www.rubydoc.info/github/svenfuchs/i18n/I18n%2FBase:with_locale) method:

```ruby
I18n.with_locale(:en) { Report.generate(for: user.role) }
```
