### ISSUE TITLE
NoMethodError: undefined method `empty?' for 0:Fixnum

### ISSUE THREAD

**Issue by amratab** [brainspec/enumerize#315]
Failing with error NoMethodError: undefined method `empty?' for 0:Fixnum . Exactly similar to https://github.com/brainspec/enumerize/issues/279

**Comment by nashby** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by amratab** [comment]
no but I have solved it by not using the method ? and using double equals. So, lets say we have user with an enum access_level with values { :admin => 0 and :super_admin => 1 } . role.admin? creates problem but role == 'admin' works fine.

**Comment by nashby** [comment]
@amratab hey, I couldn't really reproduce it so I'm going to close this issue. Try to update Enumerize version to the latest and see if that helps. Feel free to ping us when you have an app that we can use to reproduce this issue. Thanks!
