### ISSUE TITLE
Enumerize does not reload when AR does

### ISSUE THREAD

**Issue by CodingAnarchy** [brainspec/enumerize#317]
I'm trying to run some specs and my issue is that I have a validation that specifies that under certain conditions the value of an enumerized set is not allowed to change.  In the test, I set up that condition and then try to set the set (which has some contents) to `[]` in an AR update.

However, I have noticed after running this that when I do a `model.reload` to reset the dirty instance after the failed update, the Enumerize set is still empty.

**Comment by CodingAnarchy** [comment]
A sanitized example from my debug command line:

```ruby
(byebug) membership.privileges
#<Enumerize::Set {rooming}>
(byebug) membership.update(privileges: [])
false
(byebug) membership.reload
#<Membership id: 1, ... privileges: ["rooming"]>
(byebug) membership.privileges
#<Enumerize::Set {}>
```

**Comment by nashby** [comment]
@CodingAnarchy hey! It should be fixed in master. Can you please give it a try? Thanks!
