### ISSUE TITLE
Predicate should return false for a nil value

### ISSUE THREAD

**Issue by joemanley201** [brainspec/enumerize#319]
```
class User
  extend Enumerize

  enumerize :sex, in: %w(male female), predicates: true
end

user = User.new

user.male?   # => false
user.female? # => false
```
PR with a failing test here - #318 
Predicate methods should return false as per this example.
This comes from https://github.com/brainspec/enumerize/blob/master/lib/enumerize/predicates.rb#L70 where we delegate with allow_nil.

Please let me know if this is a valid issue or if you need more information.
If it is a valid issue, I can try working on a fix too.

**Comment by nashby** [comment]
closed by #318
