### ISSUE TITLE
Disable inclusion validation

### ISSUE THREAD

**Issue by chumakoff** [brainspec/enumerize#329]
I've already seen this issue https://github.com/brainspec/enumerize/issues/212, but I will repeat.

There are two problems:

1. `enumerize` adds 'inclusion' validation to the field. This behaviour is not expected.
2. There is no way to disable the validation (this problem makes the first one much worse)

**Comment by nashby** [comment]
Hey @chumakoff! Feel free to send a PR adding support for disabling validation option. Please check this comment https://github.com/brainspec/enumerize/issues/212#issuecomment-149005589 for more info.
