### ISSUE TITLE
Using bracket operator to access symbolized keys in a Hash fails

### ISSUE THREAD

**Issue by ashish91** [brainspec/enumerize#332]
If I use `Enumerize::Value` object to access the value of Hash which has symbol keys, it fails to get the value from the Hash.

```
[4] pry(main)> u.role
=> "admin"
[5] pry(main)> u.role.class
=> Enumerize::Value
[6] pry(main)> x[u.role]
=> nil
[7] pry(main)> x
=> {:admin=>"test"}
```

Is there a way to get around this ?

**Comment by nashby** [comment]
Hey, @ashish91!

One option is to use `with_indifferent_access` if you're using ActiveSupport. 

```ruby
{:admin=>"test"}.with_indifferent_access[u.role]
```
but it really depends on use case.

**Comment by ashish91** [comment]
Thanks @nashby, We're moving our application from `symbolize` gem to `enumerize` gem. We use enumerated attributes in our application to access values in Hash. So something like

```
user_permissions = { admin: 'allowed' }
user_permissions[user.state]
```

This works for `symbolize` gem since `user.state` is a symbol. However with `enumerize` gem it doesn't work out of the box. Your solution would work but it doesn't make sense to explicitly do `with_indifferent_access` everywhere we're accessing any value using enumerated value. This should be provided out of the box. What do you think ?

**Comment by mltsy** [comment]
I feel like the primary (and valid) use-case for a feature addressing this would be people migrating from another enum gem.  But a solution for this could also make certain code simpler.  Two ideas come to mind:

1. Offer an "enumerize_keys" method on Hash that would translate it into a hash that accepts an Enumerize::Value for a key
2. Offer a configuration option that causes "enumerized" fields to return a string, a symbol, or an Enumerize::Value.  This would actually be very handy for migrating from other gems (it would remove most of the catches)
