### ISSUE TITLE
Enum is not working in Rails 5, Active Support 5.2.2, enum set returns empty array always

### ISSUE THREAD

**Issue by cesar82** [brainspec/enumerize#334]
I created a new project with rails 5 and added the gem, I can save the enum correctly in the db but when I load the model from db, the attribute only returns #<Enumerize::Set {}> empty.

I tried with and without multiple and same behavior.

**Comment by nashby** [comment]
@cesar82 hey, sorry for the late response but can you please provide sample app that reproduce the issue? I'm using it in various Rails 5 projects and it works as expected.

**Comment by sedubois** [comment]
@nashby I encounter the same issue using rails 5.0.7.2, enumerize 2.3.1.

```ruby
# db/migrate/20190521060849_add_administrator_permissions.rb
class AddAdministratorPermissions < ActiveRecord::Migration[5.0]
  def change
    add_column :administrators, :roles, :string
  end
end

# app/models/administrator.rb
class Administrator < ApplicationRecord
  extend Enumerize
  ...
  serialize :roles, Array
  enumerize :roles, in: [:admin, :user_support], multiple: true
end
```

`Administrator.first.roles` initially returns `#<Enumerize::Set {}>`. I then run `Administrator.first.roles << :admin`, after which `Administrator.first.roles` still returns `#<Enumerize::Set {}>`.

**Comment by nashby** [comment]
@sedubois do you save after you run `Administrator.first.roles << :admin`?

**Comment by sedubois** [comment]
@nashby yes

![Screenshot 2019-05-21 at 13 25 10](https://user-images.githubusercontent.com/4217871/58088831-2709a880-7bcc-11e9-8721-0e941e9ba680.jpg)

**Comment by nashby** [comment]
@sedubois the thing is that you're calling save on a new object which is not modified with `:admin` changes. I'm pretty sure that following will work:

```ruby
admin = Administrator.first
admin.roles << :admin
admin.save

Administrator.first.roles # => [:admin]
```

**Comment by sedubois** [comment]
OK I think this is some feature/bug from ActiveRecord. It works when passing the data to `update` directly:

```ruby
Administrator.first.update(roles: [:admin])
Administrator.first.roles
=> #<Enumerize::Set {admin}>
```

I first tried the `<<` operator as suggested in the README but now that I check again, that was for POROs. It might be helpful to enhance the README with an ActiveRecord example of how to actually update a record.

**Comment by max223** [comment]
Would like an update on the subject if anyone has details of why is this bug is caused
