### ISSUE TITLE
Allow bracket operator to work with enumerated values

### ISSUE THREAD

**Issue by ashish91** [brainspec/enumerize#335]
Re-opening this issue, the related [issue](https://github.com/brainspec/enumerize/issues/332) was closed which didn't help solve the problem mentioned in this [comment](https://github.com/brainspec/enumerize/issues/332#issuecomment-458199535). This seems to be a bigger issue when migrating from Symbolize gem to Enumerize gem. 

Since Symbolize creates symbols the behaviour is different as compared to Enumerize gem. For accessing values in hash whose keys are made of enumerated values or when accessing a Hash with keys as symbols and using enumerated value to  access them. It doesn't work with Enumerize gem.

The provided solution in the [issue](https://github.com/brainspec/enumerize/issues/332) is to manually handle it on the app side by using `with_indifferent_access`. It's not possible to find all such occurrences using test cases.
The other way is to test all features manually and test for such issues, which is not a good option.

Is there a way we can handle this in Enumerize gem ? This makes Enumerize gem backward incompatible with Symbolize gem. And because Symbolize gem doesn't support Rails 4.2 and it's mentioned Enumerize as an alternative, most people will end up here having the same issue.

**Comment by nashby** [comment]
@ashish91 hey! I can see that this might be an issue for people migrating from Symbolize gem but we don't plan to add any support for that. We've just opened Wiki on this project so feel free to add any information you think can help people to migrate from Symbolize gem. Thanks!
