### ISSUE TITLE
returning lambda for skip validation causes active model serializer unable to dump 

### ISSUE THREAD

**Issue by saiqulhaq** [brainspec/enumerize#347]
as the title, I have stuck for 1 hour, trying to find is there any lambda or Proc in my code
I fixed my issue after deleted `skip_validation: lambda ...`
it was fine on development server, but error on production server

https://github.com/brainspec/enumerize/blob/36c38e437f539d7d78dd789eba458fb6c0653f34/test/support/shared_enums.rb#L34

https://github.com/brainspec/enumerize/pull/330

**Comment by nashby** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by saiqulhaq** [comment]
sorry I can't reproduce this issue on fresh rails 5 app
