### ISSUE TITLE
Mistaken initialization with (multiple) default value

### ISSUE THREAD

**Issue by FunkyloverOne** [brainspec/enumerize#349]
Guys, I think that the way this library sets default values for enumerized attributes is wrong.
I am referring to this part of [this method](https://github.com/brainspec/enumerize/blob/master/lib/enumerize/base.rb#L91):

```ruby
if (!attr_value || attr_value.empty?) && (!value_for_validation || value_for_validation.empty?)
  value = Utils.call_if_callable(attr.default_value, self)
  public_send("#{attr.name}=", value)
end
```

It seems convenient in most cases. But not in my case :)

I use `multiple: true` and have multiple default values.
And if an empty array was stored **intentionally** - this `if` statement is getting triggered, and here we got a set of default values instead of an empty set.

So generally, it seems like this `if` statement should not be triggered for empty arrays.

---

But that is still tricky, isn't it? Seems like this library is just "guessing" what is the desired behavior.

So maybe instead of guessing, it could be configurable? We could have an additional option like "allow_blank/empty".

Maybe not, maybe we just have to treat empty arrays different.

For singular enums, that's kinda hard to figure out whether that blank value is desired or should it be replaced with a default one. And nobody complained before, so it's most likely not worth it. :wink:

**Comment by timhwang21** [comment]
To add to this, this makes it such that enums with `multiple: true` and a default value can _never_ be set to `[]`. My use case is something like this:

```ruby
  enumerize :enabled_methods
    in: METHODS,
    default: METHODS,
    multiple: true,
```

I want to initialize with all methods enabled, but still allow methods to be disabled. However, once all methods are be disabled, the code above sets the value to be the initial value.

**Comment by nashby** [comment]
Hey! Sorry for super late reply but I don't think it's possible to do with current implementation of Enumerize. Even if we add `allow_blank` option we still can't differentiate if `[]` was set manually or it's `[]` for the newly initialised record. Yes, we can check `record.new_record?` (at least for `ActiveRecord`) and if it's true then we set `default` value and if it's false then we don't bother setting anything. This approach could work but then it's AR-specific thing. 

@timhwang21 @FunkyloverOne I'm pretty sure it's not relevant for you anymore (3 years passed already) but you can always implement this yourself by overriding initialize method and setting default values manually.

**Comment by timhwang21** [comment]
Thanks for the response! The workaround we found was to set the default
outside of enumerize in a create hook, and not set one in enumerize.
