### ISSUE TITLE
Using an ActiveRecord pluck to get values

### ISSUE THREAD

**Issue by doutatsu** [brainspec/enumerize#357]
I've tried to use pluck on the enumerized value, but instead of returning the databased stored value, it gets casted into a string. Making it impossible for me to do an `upsert` as it needs the value itself. 

Is there a way to make the pluck to return the values themselves (using `_value` doesn't work, as I get an SQL error saying there is no such column) or looking the value up in some other way, just from a string?

**Comment by nashby** [comment]
Hey @doutatsu! Apparently there was a bug in Rails and `insert_all`/`upsert_all` wasn't using typecasting. It was fixed here rails/rails#38763. So if you upgrade to Rails 6.0.3 everything will work with string

**Comment by doutatsu** [comment]
Nice, I've upgraded some time ago and can confirm it's working now :+1:

**Comment by gnclmorais** [comment]
Nice one!
![Yes!](https://media.giphy.com/media/l0HekkY2RGmwtufXq/giphy.gif)
