### ISSUE TITLE
[Documentation] Expand documentations for `only` and `except`

### ISSUE THREAD

**Issue by martinGerez** [brainspec/enumerize#359]
Hi, I think that we can expand the docs with use cases for `only` and `expand` filters.

Currently, is not so much clear in the docs, and in my own case, I needed to dig into the code to understand how we can use it.

If it is ok, I can provide some examples to add to the `README.md` :)

**Comment by nashby** [comment]
Hey @martinGerez! Sorry for late response! Yeah, feel free to send us a PR with these examples, we'll take a look, thanks!
