### ISSUE TITLE
Enumerize multiple option in mongoid 7

### ISSUE THREAD

**Issue by valentinbotog** [brainspec/enumerize#360]
Hey guys, I have a question related to enumerize gem, We upgraded all app stacks and we are using mongoid 7, and we had to change from mongoid-enum to enumerize, and we have a problem related to multiple option. The problem is no matter how I use the field + enumerize syntax  I do not have the old values which are in the DB, even after I do a mongorestore the values are not saved in field.
**Enumerize**:
field :_permissions, type: Array
  enumerize :_permissions, in: [:no_view, :view_only, :view_and_update, :full_access],
       multiple: true,
       default: [:no_view], predicates: true
  alias_method :permissions, :_permissions
Field : "_permissions"=>#<Mongoid::Fields::Standard:0x0000561f018ba8a0 @name="_permissions", @options={:default=>[:no_view], :type=>Array, :klass=>AccountPermission}, @label=nil, @default_val=[:no_view], @pre_processed=true, @type=Array>
Value: _permissions: []
**Mongoid-enum**:
enum :permissions, [:no_view, :view_only, :view_and_update, :full_access],
       multiple: true,
       default: [:no_view]
Field: "_permissions"=>#<Mongoid::Fields::Standard:0x0055e0c6324fe0 @name="_permissions", @options={:type=>Array, :default=>[:no_view], :klass=>AccountPermission}, @label=nil, @default_val=[:no_view], @pre_processed=true>
Value: _permissions: :full_access

Is there something that I missed when I changed the model field attributes from enum to enumerize?
Thank you in advance.

**Comment by nashby** [comment]
@valentinbotog Hey, sorry for late response. Right now we test enumerize against mongoid 7.0.6 and tests pass https://travis-ci.org/github/brainspec/enumerize/jobs/666485871. Could you please provide a sample application that reproduces you issue?

I'll reopen this issue when we have a way to reproduce it. Thanks!
