### ISSUE TITLE
Enumerize and multiple option in mongoid 7

### ISSUE THREAD

**Issue by bmedici** [brainspec/enumerize#363]
Hi,

When I try to use Enumerize with multiple: true in a simple Mongoid model, the attributes is considered as NIL.
Here is a simple example:

```ruby
class Blah
  include Mongoid::Document
  extend Enumerize

  enumerize :roles, multitple: true, in: [
    :free,
    :premium,
    :beta,
    :admin,
    ]

end
```

When trying in the console:

```text
> b = Blah.create
=> #<Blah _id: 5f67e18a57dd7516ddc9ad4a, >

> b.roles
=> nil

> b.roles << :admin
Traceback (most recent call last):
        1: from (irb):15
NoMethodError (undefined method `<<' for nil:NilClass)
```

Any idea of what I'm missing ?
Thanks !

# Context
enumerize (2.3.1)
      activesupport (>= 3.2)
mongoid (7.1.2)
      activemodel (>= 5.1, < 6.1)
      mongo (>= 2.7.0, < 3.0.0)

May be related to issue [#360]

**Comment by nashby** [comment]
Hey @bmedici! For `multiple` you need to serialize your field to Array like this:

```ruby
serialize :roles, Array
```

**Comment by bmedici** [comment]
Hi @nashby , thanks for you response.
However, I mentionned using Mongoid, and Mongoid should be anle to use an Array field natively, without having to serialize it.
Furthermore, serialize comes with ActiveRecord::Base which I do not use with Mongoid of course, thus serialize is not available in my model.
I was just trying to store a Enumerize-multiple field in an Array Mongoid field.

Bruno

**Comment by nashby** [comment]
@bmedici thanks for letting us know it works!
