### ISSUE TITLE
Ruby 2.7 deprecation warning: `update_all`

### ISSUE THREAD

**Issue by MichaelHoste** [brainspec/enumerize#367]
I just bumped into a deprecation warning with Ruby 2.7 when I'm using `update_all` on a model using enumerize.

```
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/enumerize-2.3.1/lib/enumerize/activerecord.rb:89: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
````

It's related to these lines: https://github.com/brainspec/enumerize/blob/ee841a8667c4cd32ae21b64bb7683e6802cba100/lib/enumerize/activerecord.rb#L85-L97

If I understand correctly links like [this](https://bloggie.io/@kinopyo/how-to-fix-ruby-2-7-warning-using-the-last-argument-as-keyword-parameters-is-deprecated#understand-the-change), `super(updates)` should become `super(**updates)`, but I'm not 100% sure.

**Comment by nashby** [comment]
hey @MichaelHoste, sorry for later response! I can't really reproduce it locally with `test/activerecord_test.rb` and Ruby 2.7. And it's pretty weird that you see that since Rails's `update_all` accepts just one `updates` parameter so I guess it shouldn't trigger that warning at all. Do you still see it?

**Comment by MichaelHoste** [comment]
Thanks for looking at this!

I really don't remember the details and I don't have the correct Ruby versions to test anymore. Since [Ruby `2.7.2`](https://www.ruby-lang.org/en/news/2020/10/02/ruby-2-7-2-released/) they disabled these annoying warnings by default so it was less of an issue for me.

I can't reproduce this warning in `2.7.4` even with `Warning[:deprecated] = true`. Maybe that specific warning was wrongly triggered in `2.7.1` and it was fixed since then?

Don't bother with that ticket, I'm closing it.
