### ISSUE TITLE
Hides ActiveModel::MissingAttributeError when default value is set

### ISSUE THREAD

**Issue by kuzukuzu** [brainspec/enumerize#376]
After #228, `ActiveModel::MissingAttributeError` is swallowed in `_set_default_value_for_enumerized_attributes` method.
As a result, it throws mysterious error when "real missing attribute error" occurred.
I encountered this phenomena with ActiveRecord.

## Steps to reproduce
Assume that model does not have attribute named `missing_attribute`, but enumerize definition for that exists.
(Migration pending also reproduces it)

```
class MyModel < ActiveRecord::Base
  extend Enumerize

  enumerize :missing_attribute, in: { a: 1, b: 2 }, default: :a
end
```

It throws error below on record initialization.

```
MyModel.new

NoMethodError:
       undefined method `empty?' for 1:Integer
     # /gems/enumerize-2.2.2/lib/enumerize/base.rb:98:in `block in _set_default_value_for_enumerized_attributes'
     # /gems/enumerize-2.2.2/lib/enumerize/attribute_map.rb:23:in `block in each'
     # /gems/enumerize-2.2.2/lib/enumerize/attribute_map.rb:22:in `each_pair'
     # /gems/enumerize-2.2.2/lib/enumerize/attribute_map.rb:22:in `each'
     # /gems/enumerize-2.2.2/lib/enumerize/base.rb:87:in `_set_default_value_for_enumerized_attributes'
     # /gems/enumerize-2.2.2/lib/enumerize/base.rb:52:in `initialize'
```

But `ActiveModel::MissingAttributeError` is expected.

## Mechanism
`_set_default_value_for_enumerized_attributes` is called twice.
And on the first time, it does not throw any errors.

1. `_set_default_value_for_enumerized_attributes` is called (first time)
2. [attribute setter called](https://github.com/brainspec/enumerize/blob/ab131a29fd6f8a32b58e062ef4d223ee52bc171d/lib/enumerize/base.rb#L105)
3. [write attribute called](https://github.com/brainspec/enumerize/blob/ab131a29fd6f8a32b58e062ef4d223ee52bc171d/lib/enumerize/attribute.rb#L105)
4. In `write_attribute`, it sets `1 (Integer)` to `_enumerized_values_for_validation['missing_attribute']`. And after that, `ActiveModel::MissingAttributeError` is raised in `super` (swallowed).
5. `_set_default_value_for_enumerized_attributes` is called (second time)
6. It raises `NoMethodError`

I think the problem is that [this line](https://github.com/brainspec/enumerize/blob/ab131a29fd6f8a32b58e062ef4d223ee52bc171d/lib/enumerize/attribute.rb#L110) is not called on step 4.
But I can't come up with better solution.

## System configuration
- *ruby* 2.4.7
- *rails* 5.1.2
- *enumerize* 2.2.2

**Comment by nashby** [comment]
@kuzukuzu hey! Sorry for late response but I can't reproduce it. Probably something has changed since this bug report. Feel free to send a failing spec so we can try to fix it if it's still an issue! Thanks!
