### ISSUE TITLE
Examples on the readme could be better

### ISSUE THREAD

**Issue by diasjorge** [brainspec/enumerize#378]
I got to this repo from a Twitter mention about your code examples. 

Feel free to ignore this but at the current times perhaps choosing something different than sex or color would be more appropriate. 

This is your open source project and you don't owe anything to anybody but it'd probably make the world a nicer place. 

https://mobile.twitter.com/vrinek/status/1380119404868870147

Thanks,

Have a good day

**Comment by nbw** [comment]
https://github.com/brainspec/enumerize/pull/380
