### ISSUE TITLE
New release for Rails 7

### ISSUE THREAD

**Issue by 0x7466** [brainspec/enumerize#390]
The current version 2.4.0 on RubyGems is not compatible with Rails 7 anymore because of the removed `decorate_attribute_type` method.

I've seen that this has already been fixed in a previous [commit](https://github.com/brainspec/enumerize/commit/226b07c4c7000b9b138fd17912968532c4543328).

It would be great if you could release a new package.

My current workaround is to load the most recent code directly from the repo.
```ruby
gem "enumerize", github: "brainspec/enumerize"
```

**Comment by OskarEichler** [comment]
+1!!
