### ISSUE TITLE
enumerize gem causes rspec-matchers to load before rspec-core

### ISSUE THREAD

**Issue by rahul342** [brainspec/enumerize#392]
When `enumerize` is loaded it requires `rspec/matchers` here https://github.com/brainspec/enumerize/blob/9dd68ca36d1efed6bc4cec8557a359f34f408d47/lib/enumerize.rb#L85

if `enumerize` loads before `rspec-core` several of DSL methods defined in `rspec-expectations` gem don't get include in core Rspec classes like `describe`.  This is mainly apparent when using spring, you'll see errors like 
```undefined method `matcher' for #<Class:0x00007fe35ab34ee0>``` if you're defining a custom matcher within the example group.

- Curious, why does this gem try to require `rspec/matchers`?
- Should we also require `rspec` before loading rspec/matchers?
- Any other suggestion to handle this case?

**Comment by nashby** [comment]
@rahul342 could you please provide sample application that reproduces that issue because I couldn't reproduce?

**Comment by rahul342** [comment]
@nashby https://github.com/rahul342/enumerize_sample
Let me know if above doesn't work for you.
