### ISSUE TITLE
Could not dump table "action_items" because of following StandardError

### ISSUE THREAD

**Issue by chabgood** [brainspec/enumerize#397]
I am getting this in my schema.rb file:

 /# Could not dump table "action_items" because of following StandardError
 /#   Unknown type 'action_item_statuses' for column 'action_status'

But the app seems to work fine.  Is there a reason for this?

**Comment by nashby** [comment]
@chabgood can you please provide sample app that reproduces this error?

**Comment by chabgood** [comment]
Not at this time.

**Comment by nashby** [comment]
Alright, feel free to ping me when you have a way of reproducing it and I'll reopen it.

**Comment by chabgood** [comment]
We reproduced it by removing any trace of the gem and re ran migrations multiple times, and no "errors" in the schema.rb file.  When we put the gem back in then the "error" re appears.
