### ISSUE TITLE
Using kwargs with inheritance fails in Ruby 3.x

### ISSUE THREAD

**Issue by mortik** [brainspec/enumerize#400]
Enumerize in Ruby 3.x will raise ArgumentErrors when using key word arguments with inheritance.

I wrote a simple test to demonstrate the issue in Ruby 3.x:

```
  it 'allows initialize method with arguments for inherited classes' do
    parent_klass = Class.new do
      def initialize(argument, key_word_argument: nil); end
    end

    klass = Class.new(parent_klass) do
      extend Enumerize

      def initialize(argument, key_word_argument: nil)
        super
      end
    end

    klass.new('arg1', key_word_argument: 'kwargs1')
  end
``` 

With this test the ci pipeline for 3.0.2 fails with the current Setup https://github.com/mortik/enumerize/actions/runs/2147315560

A suggested fix would be to update the initialize method in ```lib/enumerize/base.rb``` like this:

```
    def initialize(*args, **kwargs)
      super
      _set_default_value_for_enumerized_attributes
    end
```
Pipeline for 3.0.2 is now green again https://github.com/mortik/enumerize/actions/runs/2147411321

This fix however will prevent further support for Ruby Versions < 2.7.x

I'm happy to create a pull request with the fix and the drop of 2.6 support but i wanted to post this issue here first to explain the problem.

**Comment by nashby** [comment]
@mortik hey! I'm totally ok to drop 2.6 support since EOL is 2022-04-12 (today!). And if we're dropping 2.6 support then we can use Ruby's new `...` syntax. PR is welcome!
