### ISSUE TITLE
Can `Enumerize::Value` respond to other methods?

### ISSUE THREAD

**Issue by msxavi** [brainspec/enumerize#402]
This is more of a question than an issue. 

How would you go about if I wanted to write specific behaviour for an option? Like this:

```ruby
class User < ActiveRecord::Base
  extend Enumerize
  enumerize :role, in: [:admin, :user]
end
```

Behaviour that is role-dependent.
```ruby
def can_update?
  if user.role.admin?
   true
  elsif user.role.user?
    false
  end
```

If we had the opportunity to delegate behaviour to the role object we wouldn't need if statements. e.g:

```ruby
user = User.new
user.role.can_update?
```

Potentially:

```ruby
class Admin < Enumerize::Value
  def can_update?
    true
  end
end

class User < Enumerize::Value
  def can_update?
    false
  end
end
```

Apologies if this is already available and I couldn't find it.

Thanks.

**Comment by nashby** [comment]
Hey! It's not something we support or plan to.
