### ISSUE TITLE
Enumerize gem vs ActiveRecord::Enum

### ISSUE THREAD

**Issue by fade2black** [brainspec/enumerize#403]
Does Enumerize gem do the same thing as ActiveRecord::Enum does? In other words, is there any specific reason to choose Enumerize gem over ActiveRecord::Enum?

**Comment by nashby** [comment]
Enumerize has more features than AR::Enum. To name a few: proper i18n support, support for multiple enum values https://github.com/brainspec/enumerize#array-like-attributes, forms integration
