### ISSUE TITLE
Unnecessary warnings about existing boolean method (related to #316)

### ISSUE THREAD

**Issue by 907th** [brainspec/enumerize#411]
We have many models with the following enumerized field definition:

```
DIRECTIONS = %w{in out}.freeze
enumerize :direction, in: DIRECTIONS, scope: true
```

After #316 we started to see many warnings:
```
It's not recommended to use `in` as a field value since `in?` is defined.
```

As you can see we don't use predicates which can result in `#in?` method overwriting. So all these warnings are false positives.

Enumerize should only warn when it overwrites an existing boolean-method with a new predicate-one.

**Comment by 907th** [comment]
> Enumerize should only warn when it overwrites an existing boolean-method with a new predicate-one.

If you agree with my proposal I can implement it as a PR. Please, let me know.

**Comment by nashby** [comment]
@907th hey! Sure, PR is welcome!

**Comment by nashby** [comment]
@907th it should be fixed in master. Could you please test it? Thanks!

**Comment by 907th** [comment]
@nashby Thank you very much for your fix! 🙏
