### ISSUE TITLE
Is a new release planned?

### ISSUE THREAD

**Issue by tiii** [brainspec/enumerize#417]
We are currently updating our app to ruby 3 and the latest released gem version does not work with it. The master branch already incoporates the needed changes. We are currently using the github master branch directly but we would prefer using an official release instead.

Any chance you could release a newer version of the gem? [As far as I can see, there were no new features/breaking changes introduced since the last release](https://github.com/brainspec/enumerize/compare/v2.5.0...master) apart from dropping ruby 2.6 support which has seen its end of life in march 2022.

Ruby 2.7 is reaching it's EOL by the end of this month.

**Comment by nashby** [comment]
@tiii thanks for pinging me! 2.6.0 is released! Please let me know if you have any issue.
