### ISSUE TITLE
Undefined method 'enumerize' for RSpec::ExampleGroups in Rails 7.0.4.3

### ISSUE THREAD

**Issue by mightystrong** [brainspec/enumerize#425]
After upgrading to `Rails 7.0.4.3 / Rack 2.2.6.4` enumerize is no longer included in Rspecs.

Example.
```
it { is_expected.to enumerize(:field).in(array_of_items) }
```
Fails with `Undefined method 'enumerize' for #<RSpec::ExampleGroups...`.

Current solution:

Add to `rails_helper.rb`: `require "enumerize/integrations/rspec"`

**Comment by nashby** [comment]
@mightystrong what version of enumerize are you using? can you try master branch?

**Comment by mightystrong** [comment]
@nashby -> Gemfile.lock has version `enumerize (2.6.1)`

**Comment by mightystrong** [comment]
> @mightystrong what version of enumerize are you using? can you try master branch?

I'll try using the master sometime tomorrow.

**Comment by hleb-rubanau** [comment]
@nashby I just tried using master branch, no success, same error

```
gem 'enumerize', git: 'https://github.com/brainspec/enumerize', ref: '84cb3ae165409'
```

**Comment by softwaregravy** [comment]
I am seeing this when trying to upgrade from 2.5.0 to 2.6.1. 2.5.0 is working correctly for me.

```
  undefined method `enumerize' for #<RSpec::ExampleGroups::RestrictedIrrigation::Validations "example at ./spec/models/restricted_irrigation_spec.rb:32">
```

**Comment by nashby** [comment]
could you please confirm it's working properly? I'll release a new version tomorrow.

**Comment by mightystrong** [comment]
Will check it out tomorrow @nashby, thanks!

**Comment by lancelittle101** [comment]
Pointing to the master branch fixed it for me.

**Comment by nashby** [comment]
@DivyaChandran2023 hey, new version is released!
