### ISSUE TITLE
Enumerize attribute not serializing correctly for false boolean value in PostgreSQL (again)

### ISSUE THREAD

**Issue by issei-m** [brainspec/enumerize#442]
The same bug as https://github.com/brainspec/enumerize/issues/430 appears again after upgrading Rails 7.1 from 7.0.

**Comment by nashby** [comment]
@issei-m we have this test https://github.com/brainspec/enumerize/blob/master/test/activerecord_test.rb#L674 and we run it with Rails 7.1 Gemfile. Would it be possible for you to provide a failing spec?

**Comment by issei-m** [comment]
@nashby I've attempted to reproduce it in [my branch](https://github.com/issei-m/enumerize/pull/1) but the bug I mentioned did not occur. Therefore, I'm closing this issue at this point. (If I find out more, I might reopen it.)
Thank you for your time.
