### ISSUE TITLE
Plan for the next release? The current stable release still contains the bug I reported before

### ISSUE THREAD

**Issue by issei-m** [brainspec/enumerize#444]
Hi, I reported [an issue](https://github.com/brainspec/enumerize/issues/430) related to boolean fields not being properly saved in PostgreSQL, as mentioned in the title. It has been resolved in [this PR](https://github.com/brainspec/enumerize/pull/433), but the fix has not been included in the current stable version, 2.7.0, which is actually the version in which I reported the issue.

So, I would appreciate it if you could include this fix in the next release.

Thank you.

**Comment by nashby** [comment]
@issei-m hey, sorry it took so long but [2.8.0](https://github.com/brainspec/enumerize/releases/tag/v2.8.0) is released!
