### ISSUE TITLE
Unexpected behaviour of STI models after upgrading to 2.8.0

### ISSUE THREAD

**Issue by viralpraxis** [brainspec/enumerize#447]
An MRE:

```ruby
class Theme < ApplicationRecord
  extend Enumerize

  enumerize :variant, in: %w[accent border]
end

class ThemeSpecific < Theme
  enumerize :variant, in: %w[accent border third_variant]
end
```

`ThemeSpecific` is an STI-subclass of `Theme`.

On 2.7.0 we had this behaviour:

```ruby
theme_specific = ThemeSpecific.find(...)

theme_specific.update!(variant: "third_variant") # OK, variant is `third_variant`
```

On 2.8.0:

```ruby
theme_specific = ThemeSpecific.find(...)

theme_specific.update!(variant: "third_variant") # updates the record, sets `variant` to nil
```

I'm not sure if it matters but `variant` is not an ordinary database column, it's a JSONB field (we use `jsonb_accessor` gem to make it an AR attribute).

Also, it seems like the issue is not STI-specific and happens due to subclassing

**Comment by nashby** [comment]
Hey @viralpraxis. What Rails version are you using?

**Comment by viralpraxis** [comment]
@nashby ruby MRI 3.3.0, rails 7.1.3.2

**Comment by nashby** [comment]
@viralpraxis I did a quick test with STI and everything seems to work fine. So my guess is that something is fishy with JSONB/jsonb_accessor gem. Will try to reproduce it tonight (unless you want to try to add a failing spec, that would be really helpful)

**Comment by viralpraxis** [comment]
@nashby I made a repo with reproducible behaviour https://github.com/viralpraxis/enumerize-mre 

Running with 2.8.0:

```
$ bundle exec rails test
Running 1 tests in a single process (parallelization threshold is 50)
Run options: --seed 60429

# Running:

F

Failure:
ThemeSpecificTest#test_creation [test/models/theme/specific_test.rb:11]:
Expected: nil
  Actual: "border"
```

Running with 2.7.0:

(test passes)

**Comment by nashby** [comment]
@viralpraxis thanks! I noticed if you add

```
jsonb_accessor :data, menu_variant: [:string, default: "default"]
```

to `Specific` model the test pass. So there's something strange with how `jsonb_accessor` works with STI. Will keep investigating

**Comment by nashby** [comment]
@viralpraxis this should be fixed by https://github.com/brainspec/enumerize/commit/47f0dc569a9dd2bc73e2b9fd5773fb37fe65634a. Could you please test master branch of enumerize with your app?

**Comment by viralpraxis** [comment]
@nashby I can confirm that our tests are green when running against master 👍🏻

**Comment by viralpraxis** [comment]
Hey @nashby 👋🏻 Thanks for the fix, any plans on releasing new version?

**Comment by nashby** [comment]
@viralpraxis 2.8.1 has been released! Thanks for reporting this issue and proving a sample app! ❤️
