### ISSUE TITLE
Using enum for queries in rails

### ISSUE THREAD

**Issue by reejosamuel** [brainspec/enumerize#46]
Writing a active record query using where is throwing error. please help

`User.where(:status => :approved)`

**Comment by calfzhou** [comment]
> ```ruby
> Voucher.with_status(:paid)
> ```

Is there any equivalents for Mongoid? Now my filter statement look like this:
```ruby
Voucher.where(status: Voucher.status.find_value(param)).first
```

**Comment by dreamfall** [comment]
@calfzhou unfortunately there is no support for Mongoid yet.

**Comment by calfzhou** [comment]
@dreamfall Mongoid support named scopes too, http://mongoid.org/en/mongoid/docs/querying.html#scoping

Now i manually define scopes for enumerized fields, for example
```ruby
class Voucher
  ...
  scope :by_status, ->(s) { where(status: status.find_value(s).value) }
```

And hope that `enumerize` could handle it automatically.

**Comment by dreamfall** [comment]
@calfzhou as far as I know none of the collaborators actively uses mongodb. But you can try to add named scopes support to enumerize and we will be happy to review and accept it.

**Comment by nashby** [comment]
@calfzhou hey, I just pushed mongoid support to the master. Can you please try it and report back if it works ok for you?

**Comment by calfzhou** [comment]
@nashby It works just like what I want! Thank you very much!! :+1: :+1:

**Comment by calfzhou** [comment]
Looking for a new release to use it in our project~ i tried bundle install from GitHub, but always says 
```
git://github.com/brainspec/enumerize.git (at 3682d36) is not yet checked out. Run `bundle install` first.
```

**Comment by lest** [comment]
@calfzhou The version 0.10.0 have been released. :sparkles:

**Comment by calfzhou** [comment]
Thanks very much! :star2:
